/**
 * Canonical blocker rule registry (1A.3).
 * Maps readiness signal keys → category, owners, severity base, resolution, pause behaviour.
 * Detection still consumes live 1A.2 signals — this table does not re-evaluate domain logic.
 */

import type {
  PilotBlockerCategory,
  PilotBlockerDimension,
  PilotBlockerOwner,
  PilotBlockerSeverity,
} from "../pilotControlContracts";
import type { PilotJourneyStage } from "../readiness/readinessTypes";
import type { BlockerBindingStatus } from "./blockerTypes";

export type PilotBlockerRule = {
  ruleKey: string;
  category: PilotBlockerCategory;
  dimension: PilotBlockerDimension;
  sourceSignalKey: string;
  applicableMilestones: readonly (PilotJourneyStage | "*")[];
  detectionCondition: string;
  resolutionCondition: string;
  defaultOwner: PilotBlockerOwner;
  monitoringOwner?: PilotBlockerOwner;
  escalationOwner: PilotBlockerOwner;
  baseSeverity: PilotBlockerSeverity;
  /** Absolute age seconds before attention escalation (null = use programme defaults). */
  ageAttentionSeconds: number | null;
  ageHighSeconds: number | null;
  /** Days until procedure that elevate severity. */
  procedureProximityHighDays: number | null;
  requiresPilotPause: boolean;
  dismissalAllowed: boolean;
  patientSafeSummaryAllowed: boolean;
  permissionSensitivity: string;
  implementationStatus: BlockerBindingStatus;
  title: string;
  internalSummary: string;
  patientSafeSummary?: string;
  recommendedNextAction: string;
  criticalIntegrity: boolean;
};

const ALL_STAGES: readonly (PilotJourneyStage | "*")[] = ["*"];

export const PILOT_BLOCKER_RULES: readonly PilotBlockerRule[] = [
  {
    ruleKey: "identity.cross_tenant",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.no_cross_tenant_mapping",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "signal failed / missing / unknown mandatory",
    resolutionCondition: "canonical identity ambiguity removed; no cross-tenant reference remains",
    defaultOwner: "technical",
    escalationOwner: "director",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "Cross-tenant identity concern",
    internalSummary: "Cross-tenant identity mapping detected for enrolled patient.",
    recommendedNextAction: "Pause pilot expansion and investigate cross-tenant linkage.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "identity.tenant_mismatch",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.tenant_match",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "tenant mismatch between patient and enrolment",
    resolutionCondition: "patient tenant matches enrolment tenant",
    defaultOwner: "technical",
    escalationOwner: "director",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "Tenant identity mismatch",
    internalSummary: "Patient tenant does not match pilot enrolment tenant.",
    recommendedNextAction: "Technical review required for ambiguous patient identity.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "identity.enrolment_mismatch",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.enrolment_patient_match",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "enrolment patient id does not match resolved patient",
    resolutionCondition: "enrolment and resolved patient ids align",
    defaultOwner: "clinic_manager",
    escalationOwner: "director",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "Enrolment patient mismatch",
    internalSummary: "Pilot enrolment patient does not match resolved patient identity.",
    recommendedNextAction: "Pause pilot observation and resolve wrong-patient linkage.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "identity.ambiguous_patient",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.unique_patient",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "ambiguous patient resolution",
    resolutionCondition: "unique patient resolution without remaining ambiguity",
    defaultOwner: "clinic_manager",
    escalationOwner: "technical",
    baseSeverity: "high",
    ageAttentionSeconds: 3600,
    ageHighSeconds: 86400,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired_with_limitation",
    title: "Ambiguous patient identity",
    internalSummary: "Patient identity resolution is ambiguous for this enrolment.",
    recommendedNextAction: "Technical review required for ambiguous patient identity.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "identity.app_linkage",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.app_linkage_unique",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "app auth user linked to multiple patients",
    resolutionCondition: "app linkage uniquely resolves to enrolled patient",
    defaultOwner: "technical",
    escalationOwner: "director",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "Ambiguous app identity linkage",
    internalSummary: "Patient App account links to more than one patient record.",
    recommendedNextAction: "Pause pilot expansion and investigate cross-patient app linkage.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "identity.patient_missing",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.patient_exists",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "enrolled patient record not found in tenant",
    resolutionCondition: "patient record exists in correct tenant",
    defaultOwner: "technical",
    escalationOwner: "clinic_manager",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "Patient record missing",
    internalSummary: "Enrolled patient record could not be found in the tenant.",
    recommendedNextAction: "Technical review required for missing patient identity.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "identity.duplicate_enrolment",
    category: "data_quality",
    dimension: "identity",
    sourceSignalKey: "identity.no_duplicate_active_enrolment",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "duplicate active enrolment for same patient/programme",
    resolutionCondition: "single active enrolment remains",
    defaultOwner: "clinic_manager",
    escalationOwner: "director",
    baseSeverity: "high",
    ageAttentionSeconds: 3600,
    ageHighSeconds: 86400,
    procedureProximityHighDays: null,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "Duplicate active enrolment",
    internalSummary: "More than one active pilot enrolment exists for this patient.",
    recommendedNextAction: "Clinic manager to resolve duplicate enrolment.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "identity.crm_conflict",
    category: "identity",
    dimension: "identity",
    sourceSignalKey: "identity.crm_lead_conflict",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "CRM lead patient conflict flag set",
    resolutionCondition: "CRM lead conflict cleared",
    defaultOwner: "clinic_manager",
    escalationOwner: "technical",
    baseSeverity: "high",
    ageAttentionSeconds: 3600,
    ageHighSeconds: 86400,
    procedureProximityHighDays: null,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_identity",
    implementationStatus: "wired",
    title: "CRM lead identity conflict",
    internalSummary: "CRM lead patient reference conflicts with enrolment patient.",
    recommendedNextAction: "Clinic manager to reconcile CRM lead identity.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "patient.activation",
    category: "patient_activation",
    dimension: "patient",
    sourceSignalKey: "patient.app_activation",
    applicableMilestones: ["consultation_preparation", "procedure_preparation", "postoperative_follow_up"],
    detectionCondition: "blocking missing/pending app activation after invitation",
    resolutionCondition: "app activation exists and uniquely resolves to enrolled patient",
    defaultOwner: "reception",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: true,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_app_activity",
    implementationStatus: "wired",
    title: "Patient App not activated",
    internalSummary: "Required Patient App activation remains incomplete.",
    patientSafeSummary: "Your clinic needs you to finish activating your account.",
    recommendedNextAction: "Contact the patient to complete account activation.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "patient.consent_missing",
    category: "consent",
    dimension: "patient",
    sourceSignalKey: "patient.mandatory_consent",
    applicableMilestones: ["procedure_preparation", "postoperative_follow_up"],
    detectionCondition: "mandatory consent missing/failed/unknown/blocking",
    resolutionCondition:
      "required current consent completed for correct patient/tenant; not superseded or revoked",
    defaultOwner: "clinical",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 86400,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_documents",
    implementationStatus: "wired",
    title: "Mandatory consent incomplete",
    internalSummary: "Consent is missing for the current procedure milestone.",
    patientSafeSummary: "A required form is not yet complete.",
    recommendedNextAction: "Clinical or reception team to complete required consent.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "patient.images_missing",
    category: "images",
    dimension: "patient",
    sourceSignalKey: "patient.required_image_role",
    applicableMilestones: ["consultation_preparation", "procedure_preparation"],
    detectionCondition: "required image roles missing at applicable milestone",
    resolutionCondition: "required image roles satisfied for current milestone",
    defaultOwner: "reception",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_imaging",
    implementationStatus: "wired_with_limitation",
    title: "Required images incomplete",
    internalSummary: "Required image roles remain incomplete for the current milestone.",
    patientSafeSummary: "Required photos still need to be completed.",
    recommendedNextAction: "Reception to arrange completion of required images.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "patient.action_overdue",
    category: "patient_action_overdue",
    dimension: "patient",
    sourceSignalKey: "patient.inactivity",
    applicableMilestones: ["consultation_preparation", "procedure_preparation", "postoperative_follow_up"],
    detectionCondition: "patient inactivity attention signal (not page inactivity alone)",
    resolutionCondition: "patient activity resumes within programme thresholds",
    defaultOwner: "patient",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: true,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_patient_actions",
    implementationStatus: "wired_with_limitation",
    title: "Patient action overdue",
    internalSummary: "Patient action remains overdue during an active milestone.",
    patientSafeSummary: "Your clinic is waiting on a required step from you.",
    recommendedNextAction: "Contact the patient to complete the overdue action.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "clinical.pathology_receipt",
    category: "pathology",
    dimension: "clinical",
    sourceSignalKey: "clinical.pathology_receipt",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "required pathology result missing/pending/failed",
    resolutionCondition: "canonical pathology receipt or clearance satisfies requirement",
    defaultOwner: "clinical",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinical_full",
    implementationStatus: "wired",
    title: "Pathology result outstanding",
    internalSummary: "Required pathology result remains incomplete.",
    patientSafeSummary: "Your clinic needs to complete a review.",
    recommendedNextAction: "Clinical team to obtain required pathology result.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "clinical.pathology_review",
    category: "pathology",
    dimension: "clinical",
    sourceSignalKey: "clinical.pathology_review",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "pathology received but review_required",
    resolutionCondition: "canonical clinical review or clearance satisfies frozen requirement",
    defaultOwner: "clinical",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 86400,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinical_full",
    implementationStatus: "wired",
    title: "Pathology review required",
    internalSummary: "Required pathology review remains incomplete.",
    patientSafeSummary: "Your clinic needs to complete a review.",
    recommendedNextAction: "Clinical team to review received pathology.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "clinical.pathology_clearance",
    category: "pathology",
    dimension: "clinical",
    sourceSignalKey: "clinical.pathology_clearance",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "pathology clearance failed/unknown/missing when required",
    resolutionCondition: "pathology clearance satisfied and not superseded",
    defaultOwner: "clinical",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 86400,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinical_full",
    implementationStatus: "wired",
    title: "Pathology clearance incomplete",
    internalSummary: "Required pathology clearance remains unresolved.",
    patientSafeSummary: "Your clinic needs to complete a review.",
    recommendedNextAction: "Clinical team to complete pathology clearance.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "clinical.escalation",
    category: "clinical_review",
    dimension: "clinical",
    sourceSignalKey: "clinical.clinical_escalation",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "active clinical escalation blocking readiness",
    resolutionCondition: "clinical escalation cleared in source system",
    defaultOwner: "clinical",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 3600,
    ageHighSeconds: 86400,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinical_full",
    implementationStatus: "wired",
    title: "Clinical escalation active",
    internalSummary: "An active clinical escalation is blocking readiness.",
    patientSafeSummary: "Your clinic needs to complete a review.",
    recommendedNextAction: "Clinical team to resolve the active escalation.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "clinical.approval",
    category: "clinical_review",
    dimension: "clinical",
    sourceSignalKey: "clinical.clinical_approval",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "required clinical approval unknown/missing/failed",
    resolutionCondition: "canonical clinical approval satisfied",
    defaultOwner: "clinical",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinical_full",
    implementationStatus: "wired",
    title: "Clinical approval incomplete",
    internalSummary: "Required clinical approval remains incomplete.",
    patientSafeSummary: "Your clinic needs to complete a review.",
    recommendedNextAction: "Clinical team to complete required approval.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "financial.wrong_patient_payment",
    category: "payment_reconciliation",
    dimension: "financial",
    sourceSignalKey: "financial.wrong_patient_payment",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "payment allocated to wrong patient",
    resolutionCondition: "payment allocated canonically to correct patient and obligation",
    defaultOwner: "finance",
    escalationOwner: "director",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_financial_full",
    implementationStatus: "wired",
    title: "Wrong-patient payment allocation",
    internalSummary: "A payment appears allocated to the wrong patient.",
    recommendedNextAction:
      "Pause pilot expansion and investigate wrong-patient payment allocation.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "financial.unallocated_payment",
    category: "payment_reconciliation",
    dimension: "financial",
    sourceSignalKey: "financial.unallocated_payment",
    applicableMilestones: ["procedure_preparation", "consultation_preparation"],
    detectionCondition: "unallocated payment present affecting readiness",
    resolutionCondition: "payment allocated to correct patient and obligation",
    defaultOwner: "finance",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_financial_full",
    implementationStatus: "wired_with_limitation",
    title: "Unallocated payment",
    internalSummary: "An unallocated payment is affecting financial readiness.",
    patientSafeSummary: "A required payment step is still being confirmed.",
    recommendedNextAction: "Finance team to allocate the payment to the correct invoice.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "financial.reconciliation",
    category: "payment_reconciliation",
    dimension: "financial",
    sourceSignalKey: "financial.reconciliation_exception",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "reconciliation exception flag set",
    resolutionCondition: "reconciliation exception cleared in FinancialOS",
    defaultOwner: "finance",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_financial_full",
    implementationStatus: "wired",
    title: "Payment reconciliation required",
    internalSummary: "A payment reconciliation exception remains unresolved.",
    patientSafeSummary: "A required payment step is still being confirmed.",
    recommendedNextAction: "Finance team to complete payment reconciliation.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "financial.clearance",
    category: "financial",
    dimension: "financial",
    sourceSignalKey: "financial.clearance",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "financial clearance incomplete when required",
    resolutionCondition: "canonical FinancialOS clearance or approved financial state reached",
    defaultOwner: "finance",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_financial_full",
    implementationStatus: "wired",
    title: "Financial clearance incomplete",
    internalSummary: "Deposit verification or financial clearance is unresolved.",
    patientSafeSummary: "A required payment step is still being confirmed.",
    recommendedNextAction: "Finance team to complete financial clearance.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "financial.deposit",
    category: "financial",
    dimension: "financial",
    sourceSignalKey: "financial.deposit_verified",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "required deposit not verified",
    resolutionCondition: "deposit verified in canonical clearance sources",
    defaultOwner: "finance",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_financial_full",
    implementationStatus: "wired",
    title: "Deposit verification unresolved",
    internalSummary: "Deposit verification is unresolved.",
    patientSafeSummary: "A required payment step is still being confirmed.",
    recommendedNextAction: "Finance team to verify the required deposit.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "financial.quote",
    category: "financial",
    dimension: "financial",
    sourceSignalKey: "financial.accepted_quote",
    applicableMilestones: ["procedure_preparation", "consultation_preparation"],
    detectionCondition: "accepted quote missing when required for stage",
    resolutionCondition: "quote accepted for correct patient",
    defaultOwner: "consultant",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_financial_summary",
    implementationStatus: "wired",
    title: "Quote acceptance pending",
    internalSummary: "Required quote acceptance remains incomplete.",
    patientSafeSummary: "A required payment step is still being confirmed.",
    recommendedNextAction: "Consultant to complete quote acceptance with the patient.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "operational.appointment_exists",
    category: "appointment",
    dimension: "operational",
    sourceSignalKey: "operational.appointment_exists",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "required appointment missing at procedure stage",
    resolutionCondition: "canonical booking exists for enrolled patient",
    defaultOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinic_actions",
    implementationStatus: "wired",
    title: "Procedure appointment missing",
    internalSummary: "Required procedure appointment has not been booked.",
    patientSafeSummary: "Your clinic needs to confirm an appointment.",
    recommendedNextAction: "Reception to schedule the procedure appointment.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "operational.appointment_confirmed",
    category: "appointment",
    dimension: "operational",
    sourceSignalKey: "operational.appointment_confirmed",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "appointment exists but not confirmed",
    resolutionCondition: "appointment confirmed in bookings SoR",
    defaultOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinic_actions",
    implementationStatus: "wired",
    title: "Appointment confirmation pending",
    internalSummary: "Procedure appointment confirmation remains incomplete.",
    patientSafeSummary: "Your clinic needs to confirm an appointment.",
    recommendedNextAction: "Reception to confirm the procedure appointment.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "operational.clinic_action_overdue",
    category: "clinic_action_overdue",
    dimension: "operational",
    sourceSignalKey: "operational.clinic_action_overdue",
    applicableMilestones: ["consultation_preparation", "procedure_preparation", "postoperative_follow_up"],
    detectionCondition: "clinic action overdue beyond programme threshold",
    resolutionCondition: "clinic action completed in journey SoR",
    defaultOwner: "clinic_manager",
    escalationOwner: "director",
    baseSeverity: "attention",
    ageAttentionSeconds: 28800,
    ageHighSeconds: 172800,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_clinic_actions",
    implementationStatus: "wired",
    title: "Clinic action overdue",
    internalSummary: "A clinic-owned action remains overdue.",
    patientSafeSummary: "Your clinic is completing a required step.",
    recommendedNextAction: "Clinic manager to complete the overdue clinic action.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "operational.consent_gate",
    category: "consent",
    dimension: "operational",
    sourceSignalKey: "operational.consent_gate_for_procedure",
    applicableMilestones: ["procedure_preparation"],
    detectionCondition: "procedure consent gate blocking",
    resolutionCondition: "consent gate satisfied for procedure milestone",
    defaultOwner: "clinical",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 43200,
    ageHighSeconds: 86400,
    procedureProximityHighDays: 7,
    requiresPilotPause: false,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_documents",
    implementationStatus: "wired",
    title: "Procedure consent gate incomplete",
    internalSummary: "Consent gate for procedure readiness remains incomplete.",
    patientSafeSummary: "A required form is not yet complete.",
    recommendedNextAction: "Clinical team to complete the procedure consent gate.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "technical.failed_push",
    category: "notification_delivery",
    dimension: "technical",
    sourceSignalKey: "technical.failed_push",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "failed push delivery count > 0",
    resolutionCondition:
      "required communication delivered successfully or approved alternate path satisfies requirement",
    defaultOwner: "technical",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "attention",
    ageAttentionSeconds: 14400,
    ageHighSeconds: 86400,
    procedureProximityHighDays: null,
    requiresPilotPause: false,
    dismissalAllowed: true,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_technical",
    implementationStatus: "wired",
    title: "Notification delivery failed",
    internalSummary: "A required push notification delivery failed.",
    patientSafeSummary: "A clinic message could not be delivered yet.",
    recommendedNextAction: "Technical review of notification delivery; Reception to follow up.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "technical.repeated_failure",
    category: "technical_failure",
    dimension: "technical",
    sourceSignalKey: "technical.repeated_failure",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "repeated technical failures past escalate threshold",
    resolutionCondition: "repeated failure count cleared after successful recovery",
    defaultOwner: "technical",
    monitoringOwner: "reception",
    escalationOwner: "clinic_manager",
    baseSeverity: "high",
    ageAttentionSeconds: 3600,
    ageHighSeconds: 43200,
    procedureProximityHighDays: null,
    requiresPilotPause: false,
    dismissalAllowed: true,
    patientSafeSummaryAllowed: true,
    permissionSensitivity: "detail_technical",
    implementationStatus: "wired",
    title: "Repeated technical failure",
    internalSummary: "Repeated technical delivery failures exceed programme threshold.",
    patientSafeSummary: "A clinic message could not be delivered yet.",
    recommendedNextAction: "Technical review required for repeated delivery failures.",
    criticalIntegrity: false,
  },
  {
    ruleKey: "technical.cross_patient_linkage",
    category: "integration",
    dimension: "technical",
    sourceSignalKey: "technical.cross_patient_linkage",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "cross-patient technical linkage detected",
    resolutionCondition: "no cross-patient technical linkage remains",
    defaultOwner: "technical",
    escalationOwner: "director",
    baseSeverity: "critical",
    ageAttentionSeconds: null,
    ageHighSeconds: null,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "detail_technical",
    implementationStatus: "wired",
    title: "Cross-patient technical linkage",
    internalSummary: "Technical linkage spans more than one patient.",
    recommendedNextAction:
      "Pause pilot expansion and investigate cross-patient technical linkage.",
    criticalIntegrity: true,
  },
  {
    ruleKey: "governance.approval",
    category: "governance_approval",
    dimension: "governance",
    sourceSignalKey: "governance.approval_gate",
    applicableMilestones: ALL_STAGES,
    detectionCondition: "approved operational event indicating unresolved governance gate",
    resolutionCondition: "governance approval recorded in approved event stream",
    defaultOwner: "governance",
    escalationOwner: "director",
    baseSeverity: "high",
    ageAttentionSeconds: 86400,
    ageHighSeconds: 259200,
    procedureProximityHighDays: null,
    requiresPilotPause: true,
    dismissalAllowed: false,
    patientSafeSummaryAllowed: false,
    permissionSensitivity: "overview_full",
    implementationStatus: "contract_only",
    title: "Governance approval required",
    internalSummary: "A governance approval gate remains unresolved.",
    recommendedNextAction: "Governance or director to complete the required approval.",
    criticalIntegrity: false,
  },
];

const RULES_BY_SIGNAL = new Map(
  PILOT_BLOCKER_RULES.map((r) => [r.sourceSignalKey, r] as const)
);

export function getBlockerRuleForSignal(
  sourceSignalKey: string
): PilotBlockerRule | undefined {
  return RULES_BY_SIGNAL.get(sourceSignalKey);
}

export function listBlockerRules(): readonly PilotBlockerRule[] {
  return PILOT_BLOCKER_RULES;
}

export function ruleAppliesToStage(
  rule: PilotBlockerRule,
  stage: PilotJourneyStage
): boolean {
  return rule.applicableMilestones.includes("*") || rule.applicableMilestones.includes(stage);
}
