import "server-only";

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import type { PathologyPdfInput } from "@/src/lib/pathology/pathologyTypes";

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 13;
const FOOTER_DISCLAIMER =
  "This pathology request has been generated by the treating clinician as part of the patient's hair loss or surgical assessment.";

function parseHex(hex: string | null | undefined) {
  if (!hex || typeof hex !== "string") return rgb(0.77, 0.65, 0.37);
  const m = hex.replace(/^#/, "").match(/^([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i);
  if (!m) return rgb(0.77, 0.65, 0.37);
  return rgb(parseInt(m[1], 16) / 255, parseInt(m[2], 16) / 255, parseInt(m[3], 16) / 255);
}

function wrapToWidth(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const t = text.replace(/\r\n/g, "\n").trim();
  if (!t) return [];
  const lines: string[] = [];
  for (const para of t.split("\n")) {
    const words = para.split(/\s+/).filter(Boolean);
    let cur = "";
    for (const w of words) {
      const next = cur ? `${cur} ${w}` : w;
      if (font.widthOfTextAtSize(next, size) <= maxWidth) {
        cur = next;
      } else {
        if (cur) lines.push(cur);
        if (font.widthOfTextAtSize(w, size) <= maxWidth) {
          cur = w;
        } else {
          let chunk = "";
          for (const ch of w) {
            const trial = chunk + ch;
            if (font.widthOfTextAtSize(trial, size) <= maxWidth) chunk = trial;
            else {
              if (chunk) lines.push(chunk);
              chunk = ch;
            }
          }
          cur = chunk;
        }
      }
    }
    if (cur) lines.push(cur);
  }
  return lines;
}

function drawWrapped(
  page: PDFPage,
  yRef: { y: number },
  text: string,
  size: number,
  font: PDFFont,
  color = rgb(0.1, 0.1, 0.12)
) {
  const lines = wrapToWidth(text, font, size, CONTENT_W);
  for (const ln of lines) {
    if (yRef.y < MARGIN + 80) return;
    page.drawText(ln, { x: MARGIN, y: yRef.y, size, font, color, maxWidth: CONTENT_W });
    yRef.y -= LINE_H;
  }
}

/**
 * Builds a doctor-facing pathology request PDF (pdf-lib; no external services).
 */
export async function renderPathologyBloodRequestPdfBytes(input: PathologyPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const accent = parseHex(input.branding.accentHex);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  const drawHeader = () => {
    page.drawRectangle({ x: 0, y: PAGE_H - 52, width: PAGE_W, height: 52, color: rgb(0.06, 0.1, 0.16) });
    page.drawText(input.branding.clinicName.slice(0, 80), {
      x: MARGIN,
      y: PAGE_H - 32,
      size: 14,
      font: fontBold,
      color: accent,
    });
    let yy = PAGE_H - 46;
    for (const ln of input.branding.clinicLines.slice(0, 3)) {
      if (!ln.trim()) continue;
      page.drawText(ln.slice(0, 96), { x: MARGIN, y: yy, size: 8, font, color: rgb(0.85, 0.88, 0.92) });
      yy -= 9;
    }
    y = PAGE_H - 64;
  };

  drawHeader();

  page.drawText("PATHOLOGY / BLOOD TEST REQUEST", { x: MARGIN, y, size: 16, font: fontBold, color: rgb(0.05, 0.06, 0.08) });
  y -= 28;

  const row = (label: string, value: string | null) => {
    const v = value?.trim() || "—";
    page.drawText(label, { x: MARGIN, y, size: 9, font: fontBold, color: rgb(0.35, 0.37, 0.42) });
    page.drawText(v.slice(0, 120), { x: MARGIN + 130, y, size: 9, font, color: rgb(0.05, 0.06, 0.08) });
    y -= LINE_H + 2;
  };

  row("Patient", input.patientName);
  row("Date of birth", input.dateOfBirth);
  row("Email", input.patientEmail);
  row("Phone", input.patientPhone);
  row("Request date", input.requestDate);
  row("Request ref", input.requestRef.slice(0, 36));
  row("Template", input.templateLabel);
  row("Treating clinician", input.doctorDisplayName);
  row("Laboratory / provider", "[ To be completed by patient or clinic ]");

  y -= 6;
  page.drawText("Clinical notes / indication", { x: MARGIN, y, size: 10, font: fontBold, color: rgb(0.05, 0.06, 0.08) });
  y -= 14;
  const notes = input.clinicalNotes?.trim() || "—";
  const yRef = { y };
  drawWrapped(page, yRef, notes, 9, font);
  y = yRef.y - 8;

  page.drawText("Requested tests", { x: MARGIN, y, size: 11, font: fontBold, color: rgb(0.05, 0.06, 0.08) });
  y -= 16;

  for (const t of input.tests) {
    const code = t.code?.trim();
    const line = code ? `${code} — ${t.label}` : t.label;
    const wrapped = wrapToWidth(line, font, 9, CONTENT_W);
    for (const ln of wrapped) {
      if (y < MARGIN + 120) {
        page = doc.addPage([PAGE_W, PAGE_H]);
        y = PAGE_H - MARGIN;
        page.drawText("(continued)", { x: MARGIN, y, size: 9, font, color: rgb(0.4, 0.4, 0.45) });
        y -= 18;
      }
      page.drawText(`• ${ln}`, { x: MARGIN + 8, y, size: 9, font, color: rgb(0.05, 0.06, 0.08), maxWidth: CONTENT_W - 8 });
      y -= LINE_H;
    }
  }

  y -= 16;
  if (y < MARGIN + 100) {
    page = doc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - MARGIN;
  }
  page.drawText("Authorised by", { x: MARGIN, y, size: 10, font: fontBold, color: rgb(0.05, 0.06, 0.08) });
  y -= 18;
  page.drawText("_______________________________________________", { x: MARGIN, y, size: 9, font, color: rgb(0.2, 0.2, 0.24) });
  y -= 14;
  page.drawText("Treating clinician signature", { x: MARGIN, y, size: 8, font, color: rgb(0.45, 0.45, 0.5) });
  y -= 28;

  const footY = MARGIN + 36;
  if (y < footY + 40) {
    page = doc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - MARGIN;
  }
  const footerRef = { y: Math.min(y, footY + 40) };
  drawWrapped(page, footerRef, FOOTER_DISCLAIMER, 8, font, rgb(0.35, 0.37, 0.42));

  const bytes = await doc.save();
  return bytes;
}
