import type { ConsultationFormOption, ConsultationFormOptionSetId } from "./consultationFormTypes";

export const CONSULTATION_FORM_OPTION_SETS: Record<ConsultationFormOptionSetId, ConsultationFormOption[]> = {
  norwood_scale: [
    { value: "nw1", label: "Norwood I" },
    { value: "nw2", label: "Norwood II" },
    { value: "nw2a", label: "Norwood IIa" },
    { value: "nw3", label: "Norwood III" },
    { value: "nw3v", label: "Norwood III vertex" },
    { value: "nw4", label: "Norwood IV" },
    { value: "nw5", label: "Norwood V" },
    { value: "nw5a", label: "Norwood Va" },
    { value: "nw6", label: "Norwood VI" },
    { value: "nw7", label: "Norwood VII" },
    { value: "unsure", label: "Unsure / not classifiable" },
  ],
  ludwig_scale: [
    { value: "l1", label: "Ludwig I (mild)" },
    { value: "l2", label: "Ludwig II (moderate)" },
    { value: "l3", label: "Ludwig III (severe)" },
    { value: "unsure", label: "Unsure" },
  ],
  sinclair_scale: [
    { value: "s1", label: "Sinclair 1" },
    { value: "s2", label: "Sinclair 2" },
    { value: "s3", label: "Sinclair 3" },
    { value: "s4", label: "Sinclair 4" },
    { value: "s5", label: "Sinclair 5" },
    { value: "unsure", label: "Unsure" },
  ],
  donor_quality: [
    { value: "excellent", label: "Excellent" },
    { value: "good", label: "Good" },
    { value: "fair", label: "Fair" },
    { value: "poor", label: "Poor" },
    { value: "not_assessed", label: "Not assessed" },
  ],
  /** Recipient / midscalp skin quality — same scale language as donor for consistency. */
  recipient_area_quality: [
    { value: "excellent", label: "Excellent" },
    { value: "good", label: "Good" },
    { value: "fair", label: "Fair" },
    { value: "poor", label: "Poor" },
    { value: "not_assessed", label: "Not assessed" },
  ],
  consultation_duration_band: [
    { value: "lt3m", label: "< 3 months" },
    { value: "3_12m", label: "3–12 months" },
    { value: "1_3y", label: "1–3 years" },
    { value: "3y_plus", label: "3+ years" },
    { value: "lifelong", label: "Lifelong / since adolescence" },
  ],
  consultation_primary_objective: [
    { value: "ht_primary", label: "Hair transplant (surgical) primary focus" },
    { value: "ht_plus_medical", label: "Transplant + medical therapy combined" },
    { value: "medical_non_surgical", label: "Medical / non-surgical management primary" },
    { value: "regenerative", label: "PRP / exosomes / regenerative focus" },
    { value: "repair_revision", label: "Repair or revision after prior transplant" },
    { value: "exploratory", label: "Exploratory / undecided" },
  ],
  yes_no: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
  ],
  hair_calibre: [
    { value: "fine", label: "Fine" },
    { value: "medium", label: "Medium" },
    { value: "coarse", label: "Coarse" },
    { value: "mixed", label: "Mixed" },
  ],
  scalp_condition: [
    { value: "normal", label: "Normal / healthy" },
    { value: "seborrheic", label: "Seborrheic / oily" },
    { value: "dry", label: "Dry / flaky" },
    { value: "inflamed", label: "Inflamed / erythematous" },
    { value: "scarring_concern", label: "Possible scarring alopecia" },
    { value: "other", label: "Other" },
  ],
  shedding_severity: [
    { value: "none", label: "None reported" },
    { value: "mild", label: "Mild" },
    { value: "moderate", label: "Moderate" },
    { value: "severe", label: "Severe" },
    { value: "acute_telogen", label: "Acute telogen effluvium pattern" },
  ],
  medication_tolerance: [
    { value: "good", label: "Good — no significant issues" },
    { value: "moderate", label: "Moderate — some adverse effects" },
    { value: "poor", label: "Poor — intolerant / contraindicated" },
    { value: "na", label: "Not applicable / not tried" },
  ],
  treatment_interest: [
    { value: "ht_fue", label: "Hair transplant (FUE)" },
    { value: "ht_fut", label: "Hair transplant (FUT/strip)" },
    { value: "prp", label: "PRP" },
    { value: "exosomes", label: "Exosomes / biologics" },
    { value: "medical", label: "Medical therapy (e.g. anti-androgens, minoxidil)" },
    { value: "mesotherapy", label: "Mesotherapy" },
    { value: "camouflage", label: "Camouflage fibres / cosmetic" },
    { value: "unsure", label: "Unsure — exploring options" },
  ],
  budget_range: [
    { value: "under_5k", label: "Under $5,000" },
    { value: "5k_10k", label: "$5,000 – $10,000" },
    { value: "10k_20k", label: "$10,000 – $20,000" },
    { value: "20k_plus", label: "$20,000+" },
    { value: "discuss", label: "Prefer to discuss in person" },
  ],
  urgency: [
    { value: "routine", label: "Routine (weeks)" },
    { value: "soon", label: "Soon (this month)" },
    { value: "urgent", label: "Urgent (this fortnight)" },
    { value: "asap", label: "ASAP" },
  ],
  medical_risk_flags: [
    { value: "bleeding", label: "Bleeding disorder / anticoagulation" },
    { value: "diabetes", label: "Diabetes (poor control)" },
    { value: "cardiac", label: "Significant cardiac history" },
    { value: "keloid", label: "Keloid / hypertrophic scarring tendency" },
    { value: "smoking", label: "Active smoking" },
    { value: "immunosuppression", label: "Immunosuppression" },
    { value: "psych", label: "Body dysmorphia / psychiatric concern" },
    { value: "medical_review_required", label: "Medical review / clearance required" },
    { value: "blood_tests_recommended", label: "Blood tests / pathology screening recommended" },
    { value: "progressive_loss", label: "Rapid or progressive hair loss" },
    { value: "none_reported", label: "None reported" },
  ],
  surgical_outcome_type: [
    { value: "density_natural", label: "Natural density / conservative" },
    { value: "density_high", label: "Higher density where safe" },
    { value: "hairline_conservative", label: "Conservative hairline" },
    { value: "hairline_aggressive", label: "Lower / more aggressive hairline" },
    { value: "temple_point", label: "Temple point restoration priority" },
    { value: "crown", label: "Crown coverage priority" },
  ],
  hair_loss_onset_pattern: [
    { value: "gradual", label: "Gradual thinning" },
    { value: "sudden", label: "Sudden onset" },
    { value: "patchy", label: "Patchy / focal" },
    { value: "recurrent", label: "Recurrent episodes" },
    { value: "lifelong", label: "Lifelong / since young adult" },
  ],
  family_history_pattern: [
    { value: "maternal", label: "Maternal side" },
    { value: "paternal", label: "Paternal side" },
    { value: "both", label: "Both sides" },
    { value: "none_known", label: "No known family history" },
    { value: "unknown", label: "Unknown" },
  ],
  previous_treatment_types: [
    { value: "minoxidil", label: "Minoxidil" },
    { value: "finasteride", label: "Finasteride / dutasteride" },
    { value: "prp", label: "PRP" },
    { value: "laser", label: "Low-level laser" },
    { value: "ht_prior", label: "Prior hair transplant" },
    { value: "meso", label: "Mesotherapy" },
    { value: "supplements", label: "Supplements only" },
    { value: "none", label: "None" },
  ],
  consultation_priority: [
    { value: "hairline", label: "Hairline framing" },
    { value: "density", label: "Mid-scalp density" },
    { value: "crown", label: "Crown / vertex" },
    { value: "donor", label: "Donor assessment / repair" },
    { value: "scar", label: "Scar camouflage" },
    { value: "general", label: "General medical hair loss work-up" },
  ],
  yes_no_unsure: [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
    { value: "unsure", label: "Unsure" },
  ],
  hair_loss_pattern_type: [
    { value: "diffuse", label: "Diffuse thinning" },
    { value: "crown", label: "Crown / vertex predominant" },
    { value: "hairline", label: "Hairline / frontal recession" },
    { value: "female_pattern", label: "Female pattern (mid-part / Ludwig context)" },
    { value: "patchy", label: "Patchy / focal alopecia" },
    { value: "inflammatory", label: "Inflammatory scalp pattern" },
    { value: "unknown", label: "Unclear / needs classification" },
  ],
  hli_primary_objective: [
    { value: "stabilise_shedding", label: "Stabilise shedding / stop progression" },
    { value: "regrowth_density", label: "Regrowth / density improvement" },
    { value: "longevity_program", label: "Hair Longevity program onboarding" },
    { value: "patient_twin_baseline", label: "Patient Twin / HLI baseline mapping" },
    { value: "medication_review", label: "Medication review & optimisation" },
    { value: "second_opinion", label: "Second opinion / exploratory" },
  ],
  hli_hormonal_flags: [
    { value: "pcos_pco", label: "PCOS / hyperandrogenism history" },
    { value: "postpartum", label: "Postpartum / post-hormonal shift" },
    { value: "thyroid_history", label: "Thyroid disorder (treated or suspected)" },
    { value: "hrt_contraception", label: "HRT or hormonal contraception change" },
    { value: "menopause_perimenopause", label: "Menopause / perimenopause context" },
    { value: "none_reported", label: "None reported" },
  ],
  hli_stress_sleep_flags: [
    { value: "high_stress", label: "High chronic stress" },
    { value: "acute_stress_event", label: "Recent acute stress / illness" },
    { value: "poor_sleep", label: "Poor sleep / circadian disruption" },
    { value: "burnout_fatigue", label: "Burnout / severe fatigue" },
    { value: "none_reported", label: "None reported" },
  ],
  hli_nutrition_flags: [
    { value: "low_iron_history", label: "Iron deficiency history / heavy menses" },
    { value: "restricted_diet", label: "Restrictive diet / low protein" },
    { value: "weight_fluctuation", label: "Rapid weight loss / fluctuation" },
    { value: "vitamin_d_low", label: "Vitamin D insufficiency (known)" },
    { value: "none_reported", label: "None reported" },
  ],
  hli_treatment_priority: [
    { value: "urgent_stabilisation", label: "Urgent stabilisation first" },
    { value: "parallel_labs_lifestyle", label: "Parallel labs + lifestyle" },
    { value: "gentle_escalation", label: "Gentle escalation / tolerability-led" },
    { value: "patient_led_pacing", label: "Patient-led pacing" },
  ],
  hli_treatment_timeline: [
    { value: "immediate_start", label: "Start same visit / within days" },
    { value: "2_4_weeks", label: "2–4 weeks (after labs if needed)" },
    { value: "1_3_months", label: "1–3 month horizon" },
    { value: "watchful", label: "Watchful / review scheduled" },
  ],
  hli_pathway_recommended: [
    { value: "hli_core", label: "HLI core medical pathway" },
    { value: "patient_twin_full", label: "Patient Twin — full longitudinal" },
    { value: "patient_twin_lite", label: "Patient Twin — lite monitoring" },
    { value: "labs_first", label: "Investigations-first (then twin)" },
    { value: "lifestyle_coaching", label: "Lifestyle + scalp care adjunct" },
  ],
  female_priority_focus: [
    { value: "vertex_part_density", label: "Vertex / mid-part density & part width" },
    { value: "frontal_hairline_feminisation", label: "Frontal hairline / temporal framing" },
    { value: "diffuse_volume_global", label: "Diffuse volume loss (global thinning)" },
    { value: "shedding_acute_chronic", label: "Shedding (acute or chronic)" },
    { value: "hormonal_endocrine_review", label: "Hormonal / endocrine-led review" },
    { value: "traction_scalp_health", label: "Traction pattern / scalp health" },
    { value: "regrowth_stabilisation", label: "Stabilisation then regrowth planning" },
    { value: "second_opinion_exploratory", label: "Second opinion / exploratory" },
  ],
  female_primary_objective: [
    { value: "stabilise_shedding", label: "Stabilise shedding & reduce triggers" },
    { value: "improve_density_aesthetic", label: "Improve visible density / cosmetic balance" },
    { value: "hormonal_evaluation_alignment", label: "Align care with hormonal & systemic context" },
    { value: "patient_twin_baseline", label: "Patient Twin / HLI baseline mapping" },
    { value: "pathology_first", label: "Investigations-first (labs / dermatology)" },
    { value: "medication_optimisation", label: "Medication review & tolerability-led plan" },
    { value: "long_term_longevity_program", label: "Long-term Hair Longevity program" },
    { value: "exploratory", label: "Exploratory — options not yet decided" },
  ],
  female_hair_loss_pattern_type: [
    { value: "diffuse", label: "Diffuse thinning (global)" },
    { value: "part_widening", label: "Mid-part widening / Christmas-tree pattern" },
    { value: "frontal_hairline", label: "Frontal hairline thinning" },
    { value: "temporal_thinning", label: "Temporal / lateral recession pattern" },
    { value: "patchy", label: "Patchy / focal non-scarring" },
    { value: "inflammatory", label: "Inflammatory scalp pattern (needs dermatology lens)" },
    { value: "traction", label: "Traction-related pattern" },
    { value: "mixed", label: "Mixed pattern" },
    { value: "unclear", label: "Unclear — needs closer examination" },
  ],
  female_hormonal_flags: [
    { value: "irregular_cycles", label: "Irregular menstrual cycles" },
    { value: "postpartum", label: "Postpartum / post-pregnancy hormonal shift" },
    { value: "menopause_perimenopause", label: "Menopause / perimenopause" },
    { value: "pcos_features", label: "PCOS / hyperandrogenism features" },
    { value: "hirsutism", label: "Hirsutism" },
    { value: "acne", label: "Acne (androgen-sensitive)" },
    { value: "androgenic_symptoms", label: "Other androgenic symptoms" },
    { value: "fertility_treatment", label: "Fertility treatment / IVF context" },
    { value: "contraceptive_change", label: "Recent contraceptive change" },
    { value: "hrt", label: "HRT or systemic hormone therapy" },
    { value: "other", label: "Other hormonal context (describe in notes)" },
  ],
  postpartum_status: [
    { value: "not_applicable", label: "Not applicable / not discussed" },
    { value: "within_12_weeks", label: "Within 12 weeks postpartum" },
    { value: "months_3_to_12", label: "3–12 months postpartum" },
    { value: "beyond_12_months", label: "Beyond 12 months postpartum" },
    { value: "not_recently_postpartum", label: "Not recently postpartum" },
  ],
  ferritin_history_known: [
    { value: "unknown", label: "Unknown / not discussed" },
    { value: "low_repleted", label: "Previously low — repleted" },
    { value: "low_untreated", label: "Low / suspected — not optimised" },
    { value: "normal_recent", label: "Normal on recent testing" },
    { value: "not_checked", label: "Not checked" },
  ],
  thyroid_history_known: [
    { value: "unknown", label: "Unknown / not discussed" },
    { value: "treated_euthyroid", label: "Treated — clinically euthyroid" },
    { value: "untreated_symptoms", label: "Symptoms / untreated or unstable" },
    { value: "normal_recent", label: "Normal on recent testing" },
    { value: "not_checked", label: "Not checked" },
  ],
};

export function optionsForField(field: {
  options?: ConsultationFormOption[];
  optionSet?: ConsultationFormOptionSetId;
}): ConsultationFormOption[] {
  if (field.options?.length) return field.options;
  if (field.optionSet) return CONSULTATION_FORM_OPTION_SETS[field.optionSet] ?? [];
  return [];
}
