/**
 * Guided Assist catalog — deterministic operational tips (no AI, no clinical advice).
 * FI-TRUST / UX rebuild: staff language + post-rebuild routes (Front desk, Pipeline, Money, Team).
 */

import type {
  GuidedAssistArea,
  GuidedAssistNextActionDefinition,
  GuidedAssistTipDefinition,
} from "./guidedAssistTypes";

export const GUIDED_ASSIST_TIPS: readonly GuidedAssistTipDefinition[] = [
  // —— Today / home (role-first eligible when `roles` is set) ——
  {
    code: "today_what_next",
    area: "reception_os",
    title: "Start with Today",
    body: "Today is your home for priorities. Use the primary rail: Calendar, Patients, Front desk, and Team. Search (Ctrl+K) finds people quickly.",
    pageKey: "",
    priority: 5,
    roles: ["all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "today_reception_front_desk",
    area: "reception_os",
    title: "Reception: open Front desk first",
    body: "After login you should land near Front desk or Today. Open Front desk for check-ins, then Calendar for reschedules. Use Pipeline for new enquiries.",
    pageKey: "",
    priority: 1,
    roles: ["reception"],
    roleScope: { workspaceProfiles: ["reception", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "today_consultant_pipeline",
    area: "reception_os",
    title: "Consultant: work Pipeline",
    body: "Your home focus is enquiries. Open Pipeline to call leads, move stages, and complete follow-ups. Open consultations from the list when visits are booked.",
    pageKey: "",
    priority: 1,
    roles: ["consultant"],
    roleScope: { workspaceProfiles: ["consultant"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "today_doctor_clinical",
    area: "consultation_os",
    title: "Doctor: clinical day list",
    body: "Open Doctor overview or Consultations for your list. Review patient history before the visit. Use Surgery for cases when planning procedures.",
    pageKey: "",
    priority: 1,
    roles: ["doctor"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Doctor overview",
    actionHrefSuffix: "doctor",
  },
  {
    code: "today_finance_money",
    area: "financial_os",
    title: "Finance: open Money",
    body: "Money is your finance hub. Review deposits and balances there. Manual payment records are tracking only — confirm bank/POS truth before surgery day.",
    pageKey: "",
    priority: 1,
    roles: ["finance"],
    roleScope: { tenantAdminRoles: ["finance_admin"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "today_admin_settings_team",
    area: "workforce_os",
    title: "Admin: Team and Settings",
    body: "Use Team for roster and access, Settings for clinic configuration, and Reports under More for performance. Keep staff roles accurate so login landings stay correct.",
    pageKey: "",
    priority: 2,
    roles: ["admin"],
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Team",
    actionHrefSuffix: "team",
  },
  {
    code: "today_setup_checklist",
    area: "analytics_os",
    title: "Finish clinic setup",
    body: "If setup is incomplete, open Settings for branding, timezone, and services. The clinic guide stays available until your first case is created.",
    pageKey: "",
    priority: 8,
    roles: ["admin", "all"],
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },

  // —— Front desk ——
  {
    code: "front_desk_today",
    area: "reception_os",
    title: "Run the day from Front desk",
    body: "Front desk shows today’s arrivals and flow. Check patients in here, then use Calendar for reschedules. This is the main day board — not a separate “reception module”.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 5,
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "director", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "tour_front_desk_empty",
    area: "reception_os",
    title: "No appointments on the board — take a tour",
    body: "Front desk has no visits for today yet. A short tour covers check-in, Calendar booking, and linking patients.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "front_desk_empty",
    tourSteps: [
      "tour_front_desk_step_calendar",
      "tour_front_desk_step_checkin",
      "tour_front_desk_step_patient",
      "tour_front_desk_step_tomorrow",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Tour me",
  },
  {
    code: "tour_front_desk_step_calendar",
    area: "reception_os",
    title: "Add today’s visits on Calendar",
    body: "Open Calendar and create consultation or treatment bookings. They appear on Front desk after save.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "tour_front_desk_step_checkin",
    area: "reception_os",
    title: "Check patients in on Front desk",
    body: "When someone arrives, use check-in on the day board so clinical staff see they are here.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_front_desk_step_patient",
    area: "reception_os",
    title: "Open the patient record",
    body: "From Front desk or search, open the patient for history and imaging. Keep identity confirmed before clinical work.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Patients",
    actionHrefSuffix: "patients",
  },
  {
    code: "tour_front_desk_step_tomorrow",
    area: "reception_os",
    title: "Prep tomorrow before close",
    body: "Use Front desk → Tomorrow to review gaps and confirm deposits before you leave.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Tomorrow",
    actionHrefSuffix: "front-desk/tomorrow",
  },
  {
    code: "ctx_morning_front_desk",
    area: "reception_os",
    title: "Morning focus: Front desk",
    body: "Start the day on Front desk and Calendar. Confirm arrivals and rooms before the first patient.",
    pageKey: "",
    priority: 4,
    contextTriggers: { timeOfDay: "morning" },
    roles: ["reception", "admin", "all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "ctx_afternoon_clinical",
    area: "consultation_os",
    title: "Afternoon focus: consults and surgery prep",
    body: "Midday is ideal for consultations and readiness checks. Open Doctor overview or Surgery for blockers (staff, room, deposit).",
    pageKey: "",
    priority: 4,
    contextTriggers: { timeOfDay: "afternoon" },
    roles: ["doctor", "consultant", "admin", "all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Open Surgery",
    actionHrefSuffix: "surgery",
  },
  {
    code: "ctx_evening_money",
    area: "financial_os",
    title: "End of day: Money closeout",
    body: "Before close, review deposits and open balances in Money. Manual records are tracking only — confirm funds with finance when needed.",
    pageKey: "",
    priority: 4,
    contextTriggers: { timeOfDay: "evening" },
    roles: ["finance", "admin", "reception", "all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 8,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "ctx_today_bookings_load",
    area: "reception_os",
    title: "Today’s schedule load",
    body: "There are {{todayBookingCount}} bookings today. Use Front desk for flow and Calendar for changes.",
    pageKey: "",
    priority: 6,
    contextTriggers: { condition: "today_bookings" },
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "ctx_open_tasks",
    area: "reception_os",
    title: "Follow-up tasks waiting",
    body: "You have {{openTaskCount}} open CRM tasks. Clear overdue items in Pipeline so nothing is missed overnight.",
    pageKey: "",
    priority: 5,
    contextTriggers: { condition: "open_tasks" },
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "reception_calendar_overview",
    area: "reception_os",
    title: "Review today’s schedule",
    body: "Confirm arrivals, staff, and rooms on the calendar before the first patient. Same-day changes should be visible here and on Front desk after refresh.",
    pageKey: "calendar",
    priority: 10,
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "director"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "reception_tomorrow_prep",
    area: "reception_os",
    title: "Prepare tomorrow",
    body: "Use Front desk → Tomorrow to spot gaps, confirm deposits, and flag bookings that need a call before you leave.",
    pageKey: "front-desk/tomorrow",
    priority: 20,
    roleScope: {
      workspaceProfiles: ["reception", "clinic_manager"],
      tenantAdminRoles: ["operations_admin"],
    },
    dismissible: true,
    snoozeHours: 12,
  },

  // —— Pipeline (CRM) ——
  {
    code: "pipeline_enquiries",
    area: "reception_os",
    title: "Work enquiries in Pipeline",
    body: "Pipeline is the single door for enquiries and follow-ups. Move stages as you call patients; open an enquiry for notes and tasks. Prefer Pipeline over older enquiry bookmark URLs.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 8,
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager", "director"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "New enquiry tip",
    actionHrefSuffix: "crm",
  },
  {
    code: "tour_pipeline_empty",
    area: "reception_os",
    title: "No enquiries yet — take a short tour",
    body: "Pipeline is empty. A 4-step tour shows how to capture an enquiry, move stages, and book a consult — operational steps only.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "pipeline_empty",
    tourSteps: [
      "tour_pipeline_step_capture",
      "tour_pipeline_step_stage",
      "tour_pipeline_step_open",
      "tour_pipeline_step_book",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Tour me",
  },
  {
    code: "tour_pipeline_step_capture",
    area: "reception_os",
    title: "Capture a new enquiry",
    body: "Use New / Quick create → New enquiry (or the New enquiry control on Pipeline). Enter name and contact so the lead is saved to this clinic.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_pipeline_step_stage",
    area: "reception_os",
    title: "Move pipeline stages",
    body: "After a call or email, move the card to the next stage (or use the card menu). Stages keep follow-ups visible for the whole team.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_pipeline_step_open",
    area: "reception_os",
    title: "Open the enquiry record",
    body: "Click a card to open notes, tasks, and history. Add a task if someone else needs to follow up.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_pipeline_step_book",
    area: "reception_os",
    title: "Book a consultation",
    body: "When the patient is ready, create a consultation booking from Calendar or the enquiry actions so Front desk and Doctor lists stay in sync.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "ctx_open_leads_followup",
    area: "reception_os",
    title: "Open enquiries need attention",
    body: "You have {{openLeadCount}} open enquiries in Pipeline. Work the oldest first — call or task — then move stages so nothing stalls.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 3,
    contextTriggers: { condition: "open_leads" },
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },

  // —— Consultations / doctor ——
  {
    code: "consultation_forms_runner",
    area: "consultation_os",
    title: "Complete consultation forms",
    body: "Use consultation forms to capture history and pathway decisions consistently. Save drafts before leaving. After complete, use guided hand-offs for quotes and next steps.",
    pageKey: "consultations",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: { workspaceProfiles: ["doctor", "consultant", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
  },
  {
    code: "doctor_overview",
    area: "consultation_os",
    title: "Your clinical day list",
    body: "Doctor overview lists consultations and handoffs for your role. Open a consultation to work the patient, then return here for the next visit.",
    pageKey: "doctor",
    pageKeyPrefix: true,
    priority: 8,
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open consultations",
    actionHrefSuffix: "consultations",
  },
  {
    code: "consultation_conversion_path",
    area: "consultation_os",
    title: "Watch consult-to-booking follow-ups",
    body: "Use Pipeline stages and consultation hand-offs to see where enquiries stall after consult. Focus on operational follow-ups, not clinical decisions.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 35,
    roleScope: { workspaceProfiles: ["director", "clinic_manager", "consultant"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
  },

  // —— Surgery ——
  {
    code: "surgery_pipeline_review",
    area: "surgery_os",
    title: "Review the Surgery hub",
    body: "Open Surgery for cases, readiness, and surgery day (when enabled). Resolve operational blockers — staff, room, consent, deposit — before procedure day.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["surgeon", "clinic_manager", "director", "nurse"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Surgery",
    actionHrefSuffix: "surgery",
  },
  {
    code: "surgery_readiness_checklist",
    area: "surgery_os",
    title: "Confirm surgery readiness",
    body: "Check readiness for each upcoming case: consent, plan, pathology, deposit tracking, staff and room assignment. Missing staff or room becomes high priority within 7 days of surgery.",
    pageKey: "surgery-readiness",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: { workspaceProfiles: ["surgeon", "clinic_manager", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Surgery cases",
    actionHrefSuffix: "surgery/cases",
  },
  {
    code: "cases_worklist",
    area: "surgery_os",
    title: "Use Surgery cases",
    body: "The cases worklist is your index for active surgical journeys. Prefer Surgery → Cases in navigation; deep links still work.",
    pageKey: "cases",
    pageKeyPrefix: true,
    priority: 15,
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Surgery hub",
    actionHrefSuffix: "surgery",
  },

  // —— Money ——
  {
    code: "financial_os_revenue",
    area: "financial_os",
    title: "Use Money for finance work",
    body: "Money is the finance hub: deposits, balances, pathways, and collection priorities. Manual payment records are operational tracking — not bank proof. Verify funds before surgery day.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "tour_money_empty",
    area: "financial_os",
    title: "No payment records yet — take a tour",
    body: "Money has no tracked payment rows yet. Tour how deposits, clearance, and the payment inbox relate — tracking only, not bank settlement.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "money_empty",
    tourSteps: [
      "tour_money_step_hub",
      "tour_money_step_deposit",
      "tour_money_step_clearance",
      "tour_money_step_inbox",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Tour me",
  },
  {
    code: "tour_money_step_hub",
    area: "financial_os",
    title: "Money is the single finance door",
    body: "Use More → Money for invoices, deposits, and pathways. Avoid treating badges as bank proof without finance sign-off.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_money_step_deposit",
    area: "financial_os",
    title: "Record a surgery deposit",
    body: "Create a manual payment record when a deposit is taken. Mark paid only after funds are verified.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_money_step_clearance",
    area: "financial_os",
    title: "Clearance before surgery confirm",
    body: "Surgery confirmation within 14 days can block if clearance is not ready. Resolve deposit or pathway items in Money first.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Surgery readiness",
    actionHrefSuffix: "surgery-readiness",
  },
  {
    code: "tour_money_step_inbox",
    area: "financial_os",
    title: "Take payment when enabled",
    body: "If online payments are on, use Take payment from Money. Otherwise keep using manual records under financial payments.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_surgery_empty",
    area: "surgery_os",
    title: "No open surgery cases — take a tour",
    body: "Surgery has no open cases yet. Tour how cases, readiness, and booking connect.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "surgery_empty",
    tourSteps: [
      "tour_surgery_step_case",
      "tour_surgery_step_readiness",
      "tour_surgery_step_book",
      "tour_surgery_step_day",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Tour me",
  },
  {
    code: "tour_surgery_step_case",
    area: "surgery_os",
    title: "Create a surgery case",
    body: "Use New case (or Surgery → cases) after consult so planning and readiness have a home record.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "New case",
    actionHrefSuffix: "cases/new",
  },
  {
    code: "tour_surgery_step_readiness",
    area: "surgery_os",
    title: "Check readiness blockers",
    body: "Open readiness for consent, plan, deposit, staff, and room. Fix gaps before confirming the booking.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Readiness",
    actionHrefSuffix: "surgery-readiness",
  },
  {
    code: "tour_surgery_step_book",
    area: "surgery_os",
    title: "Book the procedure on Calendar",
    body: "Create a surgery booking linked to the case. Assign surgeon and room so readiness can clear.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "tour_surgery_step_day",
    area: "surgery_os",
    title: "Surgery day board",
    body: "On procedure day, use Surgery day (when enabled) for live flow. Keep Money clearance verified before start.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_calendar_empty",
    area: "reception_os",
    title: "Calendar has no visits today — tour booking",
    body: "Nothing is scheduled for today. Tour how to book a consultation and see it on Front desk.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "calendar_empty",
    tourSteps: [
      "tour_calendar_step_book",
      "tour_calendar_step_resources",
      "tour_calendar_step_front_desk",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Tour me",
  },
  {
    code: "tour_calendar_step_book",
    area: "reception_os",
    title: "Create a booking",
    body: "Use New booking or click a free slot. Choose consultation or treatment type and save.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_calendar_step_resources",
    area: "reception_os",
    title: "Assign staff and room",
    body: "Set clinician and room when your clinic uses them so readiness and Front desk stay accurate.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_calendar_step_front_desk",
    area: "reception_os",
    title: "See it on Front desk",
    body: "After save, open Front desk to manage arrivals for the same day.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "payments_inbox",
    area: "financial_os",
    title: "Take payment or record deposits",
    body: "When online payments are enabled, use Take payment from Money. Otherwise record deposits under Money / financial payments. Escalate mismatches to finance admin.",
    pageKey: "payments",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: {
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
      workspaceProfiles: ["director", "reception"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },

  // —— Team / training ——
  {
    code: "team_directory",
    area: "workforce_os",
    title: "Keep Team records current",
    body: "Use Team for staff list, roster, onboarding, and access. Keep roles and contact details accurate so login landing and permissions stay correct.",
    pageKey: "team",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Team",
    actionHrefSuffix: "team",
  },
  {
    code: "workforce_staff_directory",
    area: "workforce_os",
    title: "Staff directory under Team",
    body: "Staff profiles live under Team. When someone joins or changes role, update Team and staff access so they land on the right home after login.",
    pageKey: "staff",
    pageKeyPrefix: true,
    priority: 12,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Team staff",
    actionHrefSuffix: "team/staff",
  },
  {
    code: "workforce_hr_sync",
    area: "workforce_os",
    title: "Review team compliance and access",
    body: "From Team, open compliance, training, and access tabs for onboarding gaps. Fix data issues before rostering staff onto clinical days.",
    pageKey: "team",
    pageKeyPrefix: true,
    priority: 25,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
  },
  {
    code: "academy_training_tracks",
    area: "academy_os",
    title: "Training and competencies",
    body: "Training tracks and competencies live under Team where available. Confirm new hires are enrolled after onboarding.",
    pageKey: "team/training",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["academy_trainer", "director", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Team training",
    actionHrefSuffix: "team/training",
  },

  // —— Reports ——
  {
    code: "analytics_operations_dashboard",
    area: "analytics_os",
    title: "Review Reports",
    body: "Reports holds analytics, quality, surgery, and performance views. Use it for clinic trends — not individual clinical decisions. Reports is under More on the primary rail.",
    pageKey: "reports",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "auditor"],
      tenantAdminRoles: ["dashboard_viewer", "data_safety_admin", "finance_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Reports",
    actionHrefSuffix: "reports",
  },

  // —— Settings / onboarding ——
  {
    code: "onboarding_configuration_hub",
    area: "analytics_os",
    title: "Finish clinic configuration",
    body: "Complete branding, timezone, and contact details in Settings so bookings, invoices, and communications resolve correctly.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 1,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 12,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },
  {
    code: "onboarding_first_case",
    area: "reception_os",
    title: "Create your first patient case",
    body: "Use New case (or Surgery → new case) to add a person, patient, and case. That unlocks consultations, imaging, and surgery workflows.",
    pageKey: "cases/new",
    priority: 2,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "reception"],
      tenantAdminRoles: ["clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 12,
    actionLabel: "New case",
    actionHrefSuffix: "cases/new",
  },
  {
    code: "onboarding_connect_existing_systems",
    area: "analytics_os",
    title: "Connect existing systems",
    body: "Register legacy CRM, calendar, or finance tools under Settings for coexistence during onboarding. Verify credentials before any live sync.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 3,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },
  {
    code: "onboarding_verify_existing_systems",
    area: "analytics_os",
    title: "Verify connector credentials",
    body: "After registering external systems, verify credentials and scopes before live sync. Test-mode only until you go live.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 4,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },
  {
    code: "patients_directory",
    area: "reception_os",
    title: "Find people in Patients",
    body: "Patients is the directory for care records. Use search for name or phone. Open a patient for timeline, imaging, and linked enquiries.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 12,
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
  },
];

export const GUIDED_ASSIST_NEXT_ACTIONS: readonly GuidedAssistNextActionDefinition[] = [
  {
    code: "next_create_organisation",
    area: "analytics_os",
    title: "Create an organisation",
    description: "Every clinic belongs to an organisation. Start in the directory.",
    hrefSuffix: "directory",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 1,
    requiresSetupFlags: { organisationCreated: false },
  },
  {
    code: "next_create_clinic",
    area: "analytics_os",
    title: "Create a clinic",
    description: "Add at least one clinic under your organisation.",
    hrefSuffix: "directory",
    roleScope: {
      tenantAdminRoles: ["clinic_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 2,
    requiresSetupFlags: { organisationCreated: true, clinicCreated: false },
  },
  {
    code: "next_complete_configuration",
    area: "analytics_os",
    title: "Complete clinic configuration",
    description: "Finish clinic contact, timezone, and branding in Settings.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 3,
    requiresSetupFlags: { clinicCreated: true, clinicSettingsComplete: false },
  },
  {
    code: "next_connect_existing_systems",
    area: "analytics_os",
    title: "Connect existing systems",
    description: "Register legacy CRM, calendar, finance, or marketing tools without immediate migration.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 4,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_verify_connector_permissions",
    area: "analytics_os",
    title: "Verify connector permissions",
    description: "Confirm external system credentials and required API scopes before live sync.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 5,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_first_case",
    area: "reception_os",
    title: "Create your first patient case",
    description: "Use the guided wizard to add your first active case.",
    hrefSuffix: "cases/new",
    roleScope: { anyRole: true },
    priority: 6,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_open_front_desk",
    area: "reception_os",
    title: "Open Front desk",
    description: "Foundation setup is complete. Run today’s clinic board from Front desk.",
    hrefSuffix: "front-desk",
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "nurse"], anyRole: false },
    priority: 9,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_open_calendar",
    area: "reception_os",
    title: "Open today's calendar",
    description: "Review today’s schedule and assignments.",
    hrefSuffix: "calendar",
    roleScope: { workspaceProfiles: ["reception", "clinic_manager"], anyRole: false },
    priority: 10,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_open_pipeline",
    area: "reception_os",
    title: "Open Pipeline",
    description: "Work enquiries and follow-ups from the single Pipeline door.",
    hrefSuffix: "crm",
    roleScope: { workspaceProfiles: ["consultant", "reception", "clinic_manager"], anyRole: false },
    priority: 10,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_review_surgery_pipeline",
    area: "surgery_os",
    title: "Review Surgery",
    description: "Check cases awaiting readiness or scheduling.",
    hrefSuffix: "surgery",
    roleScope: { workspaceProfiles: ["surgeon", "clinic_manager", "director", "nurse"] },
    priority: 11,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_financial_overview",
    area: "financial_os",
    title: "Review Money",
    description: "Confirm deposits, invoices, and receivables. Manual records are not bank proof.",
    hrefSuffix: "financial-os",
    roleScope: {
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
      workspaceProfiles: ["director"],
    },
    priority: 12,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_academy_enrolment",
    area: "academy_os",
    title: "Enrol staff in training",
    description: "Assign training tracks from Team for new team members.",
    hrefSuffix: "team/training",
    roleScope: { workspaceProfiles: ["academy_trainer", "director", "clinic_manager"] },
    priority: 13,
    requiresSetupFlags: { firstCaseCreated: true },
  },
];

export function listGuidedAssistTipsForArea(
  area: GuidedAssistArea
): readonly GuidedAssistTipDefinition[] {
  return GUIDED_ASSIST_TIPS.filter((t) => t.area === area);
}

export function getGuidedAssistTipByCode(code: string): GuidedAssistTipDefinition | null {
  const c = code.trim();
  return GUIDED_ASSIST_TIPS.find((t) => t.code === c) ?? null;
}
