/**
 * OnboardingOS Phase D — deterministic guided assist catalog (no AI, no clinical advice).
 */

import type {
  GuidedAssistArea,
  GuidedAssistNextActionDefinition,
  GuidedAssistTipDefinition,
} from "./guidedAssistTypes";

export const GUIDED_ASSIST_TIPS: readonly GuidedAssistTipDefinition[] = [
  // ReceptionOS
  {
    code: "reception_calendar_overview",
    area: "reception_os",
    title: "Review today's schedule",
    body: "Open the calendar to confirm arrivals, room assignments, and any same-day changes before patients check in.",
    pageKey: "calendar",
    priority: 10,
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "director"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "reception_tomorrow_prep",
    area: "reception_os",
    title: "Prepare tomorrow's board",
    body: "Use Tomorrow view to spot gaps, confirm deposits, and flag bookings that need follow-up before end of day.",
    pageKey: "tomorrow",
    priority: 20,
    roleScope: {
      workspaceProfiles: ["reception", "clinic_manager"],
      tenantAdminRoles: ["operations_admin"],
    },
    dismissible: true,
    snoozeHours: 12,
  },
  {
    code: "reception_os_hub",
    area: "reception_os",
    title: "ReceptionOS communication hub",
    body: "ReceptionOS centralises check-in, deposits, and patient communications. Start from the hub when coordinating front desk tasks.",
    pageKey: "reception-os",
    pageKeyPrefix: true,
    priority: 5,
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "director"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
  },
  // ConsultationOS
  {
    code: "consultation_forms_runner",
    area: "consultation_os",
    title: "Complete structured consultation forms",
    body: "Use ConsultationOS forms to capture history, consent, and pathway decisions consistently. Save drafts before leaving the page.",
    pageKey: "consultations",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: { workspaceProfiles: ["doctor", "consultant", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
  },
  {
    code: "consultation_conversion_path",
    area: "consultation_os",
    title: "Track consultation conversion",
    body: "Review consultation conversion to see where enquiries stall between consult and booking. Focus on operational follow-ups, not clinical decisions.",
    pageKey: "consultation-conversion",
    pageKeyPrefix: true,
    priority: 30,
    roleScope: { workspaceProfiles: ["director", "clinic_manager", "consultant"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
  },
  // SurgeryOS
  {
    code: "surgery_pipeline_review",
    area: "surgery_os",
    title: "Review the surgery pipeline",
    body: "Check SurgeryOS for cases awaiting readiness, scheduling, or documentation. Resolve operational blockers before procedure day.",
    pageKey: "surgery-os",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["surgeon", "clinic_manager", "director", "nurse"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open SurgeryOS",
    actionHrefSuffix: "surgery-os",
  },
  {
    code: "surgery_readiness_checklist",
    area: "surgery_os",
    title: "Confirm surgery readiness items",
    body: "Open surgery readiness for each active case and verify administrative prerequisites are complete (consents filed, deposits recorded, dates confirmed).",
    pageKey: "surgery-readiness",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: { workspaceProfiles: ["surgeon", "clinic_manager", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
  },
  {
    code: "cases_worklist",
    area: "surgery_os",
    title: "Use the cases worklist",
    body: "The cases list is your operational index for active patient journeys. Filter by stage to prioritise documentation and scheduling tasks.",
    pageKey: "cases",
    pageKeyPrefix: true,
    priority: 15,
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
  },
  // FinancialOS
  {
    code: "financial_os_revenue",
    area: "financial_os",
    title: "Monitor revenue and receivables",
    body: "FinancialOS summarises invoices, deposits, and outstanding balances. Review weekly with your finance admin — no automated payment advice is generated here.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open FinancialOS",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "payments_inbox",
    area: "financial_os",
    title: "Process the payments inbox",
    body: "Match incoming payments to cases and mark records reconciled. Escalate discrepancies to finance admin rather than adjusting clinical records.",
    pageKey: "payments",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: {
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
      workspaceProfiles: ["director"],
    },
    dismissible: true,
    snoozeHours: 24,
  },
  // AcademyOS
  {
    code: "academy_training_tracks",
    area: "academy_os",
    title: "Assign mandatory training tracks",
    body: "AcademyOS tracks competency and procedure privileges. Confirm staff are enrolled in the correct tracks after onboarding new team members.",
    pageKey: "academy",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["academy_trainer", "director", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open AcademyOS",
    actionHrefSuffix: "academy",
  },
  // WorkforceOS
  {
    code: "workforce_staff_directory",
    area: "workforce_os",
    title: "Keep the staff directory current",
    body: "Verify roles, contact details, and feature access templates whenever someone joins or changes position. WorkforceOS relies on accurate staff records.",
    pageKey: "staff",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
  },
  {
    code: "workforce_hr_sync",
    area: "workforce_os",
    title: "Review HR sync health",
    body: "Check HR OS sync status for onboarding gaps, missing URLs, or readiness flags. Resolve data issues before rostering staff to clinical workflows.",
    pageKey: "hr-os",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
  },
  // AnalyticsOS
  {
    code: "analytics_operations_dashboard",
    area: "analytics_os",
    title: "Review operational metrics",
    body: "AnalyticsOS aggregates module events for clinic health. Use it for trend review and operational planning — not for individual patient clinical decisions.",
    pageKey: "operations",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "auditor"],
      tenantAdminRoles: ["dashboard_viewer", "data_safety_admin", "finance_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
  },
  {
    code: "analytics_home_checklist",
    area: "analytics_os",
    title: "Track setup progress on home",
    body: "Your FI home dashboard shows foundation checklist progress. Complete each item to unlock the full operational workspace.",
    pageKey: "",
    priority: 5,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 24,
  },
  // Onboarding — cross-area setup tips
  {
    code: "onboarding_configuration_hub",
    area: "analytics_os",
    title: "Finish clinic configuration",
    body: "Complete branding, timezone, and contact details in the configuration hub so bookings, invoices, and patient communications resolve correctly.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 1,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 12,
    actionLabel: "Open configuration",
    actionHrefSuffix: "configuration",
  },
  {
    code: "onboarding_first_case",
    area: "reception_os",
    title: "Create your first patient case",
    body: "Run the new case wizard to add a person, patient record, and case in one flow. This unlocks consultations, imaging, and surgery workflows.",
    pageKey: "cases/new",
    priority: 2,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "reception"],
      tenantAdminRoles: ["clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 12,
    actionLabel: "New case wizard",
    actionHrefSuffix: "cases/new",
  },
  {
    code: "onboarding_connect_existing_systems",
    area: "analytics_os",
    title: "Connect existing systems",
    body: "Register legacy CRM, calendar, finance, or marketing tools for coexistence during onboarding. No data migration required yet — architecture foundation only.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 3,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Connect systems",
    actionHrefSuffix: "configuration",
  },
  {
    code: "onboarding_verify_existing_systems",
    area: "analytics_os",
    title: "Verify connector credentials",
    body: "After registering external systems, verify credentials and permission scopes before any live sync is enabled. Test-mode verification only — no data is imported yet.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 4,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Verify connectors",
    actionHrefSuffix: "configuration",
  },
];

export const GUIDED_ASSIST_NEXT_ACTIONS: readonly GuidedAssistNextActionDefinition[] = [
  {
    code: "next_create_organisation",
    area: "analytics_os",
    title: "Create an organisation",
    description: "Every clinic belongs to an organisation. Start in the directory.",
    hrefSuffix: "directory",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 1,
    requiresSetupFlags: { organisationCreated: false },
  },
  {
    code: "next_create_clinic",
    area: "analytics_os",
    title: "Create a clinic",
    description: "Add at least one clinic under your organisation.",
    hrefSuffix: "directory",
    roleScope: {
      tenantAdminRoles: ["clinic_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 2,
    requiresSetupFlags: { organisationCreated: true, clinicCreated: false },
  },
  {
    code: "next_complete_configuration",
    area: "analytics_os",
    title: "Complete clinic configuration",
    description: "Finish clinic contact, timezone, and branding settings.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 3,
    requiresSetupFlags: { clinicCreated: true, clinicSettingsComplete: false },
  },
  {
    code: "next_connect_existing_systems",
    area: "analytics_os",
    title: "Connect existing systems",
    description:
      "Register legacy CRM, calendar, finance, or marketing tools without immediate migration.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 4,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_verify_connector_permissions",
    area: "analytics_os",
    title: "Verify connector permissions",
    description: "Confirm external system credentials and required API scopes before live sync.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 5,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_first_case",
    area: "reception_os",
    title: "Create your first patient case",
    description: "Use the guided wizard to add your first active case.",
    hrefSuffix: "cases/new",
    roleScope: { anyRole: true },
    priority: 6,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_open_calendar",
    area: "reception_os",
    title: "Open today's calendar",
    description: "Foundation setup is complete. Review today's schedule.",
    hrefSuffix: "calendar",
    roleScope: { workspaceProfiles: ["reception", "clinic_manager"], anyRole: false },
    priority: 10,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_review_surgery_pipeline",
    area: "surgery_os",
    title: "Review surgery pipeline",
    description: "Check cases awaiting readiness or scheduling.",
    hrefSuffix: "surgery-os",
    roleScope: { workspaceProfiles: ["surgeon", "clinic_manager", "director", "nurse"] },
    priority: 11,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_financial_overview",
    area: "financial_os",
    title: "Review FinancialOS",
    description: "Confirm invoices, deposits, and receivables are configured.",
    hrefSuffix: "financial-os",
    roleScope: {
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
      workspaceProfiles: ["director"],
    },
    priority: 12,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_academy_enrolment",
    area: "academy_os",
    title: "Enrol staff in AcademyOS",
    description: "Assign training tracks for new team members.",
    hrefSuffix: "academy",
    roleScope: { workspaceProfiles: ["academy_trainer", "director", "clinic_manager"] },
    priority: 13,
    requiresSetupFlags: { firstCaseCreated: true },
  },
];

export function listGuidedAssistTipsForArea(
  area: GuidedAssistArea
): readonly GuidedAssistTipDefinition[] {
  return GUIDED_ASSIST_TIPS.filter((t) => t.area === area);
}

export function getGuidedAssistTipByCode(code: string): GuidedAssistTipDefinition | null {
  const c = code.trim();
  return GUIDED_ASSIST_TIPS.find((t) => t.code === c) ?? null;
}
