/**
 * Clinic guide catalog — warm, human operational tips (no AI, no clinical advice).
 * Tone: helpful colleague guiding staff through a new system.
 * Routes: Front desk, Pipeline, Money, Team, Doctor, Patients, Imaging.
 */

import type {
  GuidedAssistArea,
  GuidedAssistNextActionDefinition,
  GuidedAssistQuickActionDefinition,
  GuidedAssistTipDefinition,
} from "./guidedAssistTypes";

export const GUIDED_ASSIST_TIPS: readonly GuidedAssistTipDefinition[] = [
  // —— Today / home (role-first eligible when `roles` is set) ——
  {
    code: "today_what_next",
    area: "reception_os",
    title: "Let’s find your footing on Today",
    body: "You’re in the right place. Today is home base for priorities — Calendar, Patients, Front desk, and Team sit on the primary rail. Search (Ctrl+K) is a friendly shortcut when you need someone fast. No pressure — take it one step at a time.",
    pageKey: "",
    priority: 5,
    roles: ["all"],
    roleGroup: "core",
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "today_reception_front_desk",
    area: "reception_os",
    title: "Let’s get your morning front desk sorted",
    body: "Start with Front desk for arrivals and check-ins — that’s the calm centre of the day. Use Calendar only when something needs moving. Pipeline is for enquiries, not walk-in check-in. You’ve got this.",
    pageKey: "",
    priority: 1,
    roles: ["reception"],
    roleGroup: "support",
    roleScope: { workspaceProfiles: ["reception"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "today_consultant_pipeline",
    area: "consultation_os",
    title: "Here’s a gentle path through Pipeline",
    body: "When you’re ready, open Pipeline and work the oldest enquiry first. A short note or task, then move the stage — small steps that keep the team in sync. Book consults from Calendar so Doctor and Front desk stay aligned. Operational routing only — never clinical advice.",
    pageKey: "",
    priority: 1,
    roles: ["consultant"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["consultant"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "today_doctor_clinical",
    area: "consultation_os",
    title: "Here’s a quick way to review today’s patients",
    body: "Open Doctor overview or Consultations for your list. From there you can open a patient for history, imaging, and forms before the visit. Surgery is for case planning when you need it. This guide only helps you navigate the system — clinical decisions stay with you.",
    pageKey: "",
    priority: 1,
    roles: ["doctor"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Doctor overview",
    actionHrefSuffix: "doctor",
  },
  {
    code: "today_nurse_day_flow",
    area: "consultation_os",
    title: "Let’s walk through a smooth clinical day",
    body: "Front desk shows who’s here; Patients and Doctor/Consultations help you open the right record quickly. Imaging and forms live on the patient and consultation screens. No worries if this is new — open one patient at a time and the system will feel familiar soon.",
    pageKey: "",
    priority: 1,
    roles: ["nurse"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "today_finance_money",
    area: "financial_os",
    title: "Let’s open Money with confidence",
    body: "Money is your calm finance hub for deposits, balances, and pathways. Manual payment rows are tracking only — confirm bank/POS before surgery day. When you’re ready, open Money and work one list at a time.",
    pageKey: "",
    priority: 1,
    roles: ["finance"],
    roleGroup: "support",
    roleScope: { tenantAdminRoles: ["finance_admin"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "today_admin_settings_team",
    area: "workforce_os",
    title: "Admin home: Team and Settings, gently",
    body: "Use Team for roster and access, Settings for clinic configuration, and Reports under More when you need trends. Keeping roles accurate helps everyone land in the right place after login. You’re supporting the whole clinic — one clear step at a time.",
    pageKey: "",
    priority: 2,
    roles: ["admin"],
    roleGroup: "support",
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Team",
    actionHrefSuffix: "team",
  },
  {
    code: "today_setup_checklist",
    area: "analytics_os",
    title: "When you’re ready, finish clinic setup",
    body: "If anything in setup still feels unfinished, open Settings for branding, timezone, and services. The clinic guide stays nearby until your first case is created — no rush, we’ll keep nudging the next step only.",
    pageKey: "",
    priority: 8,
    roles: ["admin", "all"],
    roleGroup: "core",
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },

  // —— Front desk ——
  {
    code: "front_desk_today",
    area: "reception_os",
    title: "Run the day from Front desk",
    body: "Front desk shows today’s arrivals and flow. Check patients in here, then use Calendar for reschedules. This is the main day board — not a separate “reception module”.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 5,
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "director", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "tour_front_desk_empty",
    area: "reception_os",
    title: "No appointments on the board — take a tour",
    body: "Front desk has no visits for today yet. A short tour covers check-in, Calendar booking, and linking patients.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "front_desk_empty",
    tourSteps: [
      "tour_front_desk_step_calendar",
      "tour_front_desk_step_checkin",
      "tour_front_desk_step_patient",
      "tour_front_desk_step_tomorrow",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Tour me",
  },
  {
    code: "tour_front_desk_step_calendar",
    area: "reception_os",
    title: "Add today’s visits on Calendar",
    body: "Open Calendar and create consultation or treatment bookings. They appear on Front desk after save.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "tour_front_desk_step_checkin",
    area: "reception_os",
    title: "Check patients in on Front desk",
    body: "When someone arrives, use check-in on the day board so clinical staff see they are here.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_front_desk_step_patient",
    area: "reception_os",
    title: "Open the patient record",
    body: "From Front desk or search, open the patient for history and imaging. Keep identity confirmed before clinical work.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Patients",
    actionHrefSuffix: "patients",
  },
  {
    code: "tour_front_desk_step_tomorrow",
    area: "reception_os",
    title: "Prep tomorrow before close",
    body: "Use Front desk → Tomorrow to review gaps and confirm deposits before you leave.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Tomorrow",
    actionHrefSuffix: "front-desk/tomorrow",
  },
  {
    code: "ctx_morning_front_desk",
    area: "reception_os",
    title: "Let’s get your morning front desk sorted",
    body: "A calm start: open Front desk and Calendar, confirm arrivals and rooms before the first patient. Small checks now save a busy afternoon later.",
    pageKey: "",
    priority: 4,
    contextTriggers: { timeOfDay: "morning" },
    roles: ["reception", "admin", "nurse", "all"],
    roleGroup: "core",
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "ctx_afternoon_clinical",
    area: "consultation_os",
    title: "Afternoon focus: consults and surgery prep",
    body: "Midday is ideal for consultations and readiness checks. Open Doctor overview or Surgery for blockers (staff, room, deposit).",
    pageKey: "",
    priority: 4,
    contextTriggers: { timeOfDay: "afternoon" },
    roles: ["doctor", "consultant", "admin", "all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Open Surgery",
    actionHrefSuffix: "surgery",
  },
  {
    code: "ctx_evening_money",
    area: "financial_os",
    title: "End of day: Money closeout",
    body: "Before close, review deposits and open balances in Money. Manual records are tracking only — confirm funds with finance when needed.",
    pageKey: "",
    priority: 4,
    contextTriggers: { timeOfDay: "evening" },
    roles: ["finance", "admin", "reception", "all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 8,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "ctx_today_bookings_load",
    area: "reception_os",
    title: "Today’s schedule load",
    body: "There are {{todayBookingCount}} bookings today. Use Front desk for flow and Calendar for changes.",
    pageKey: "",
    priority: 6,
    contextTriggers: { condition: "today_bookings" },
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "ctx_open_tasks",
    area: "reception_os",
    title: "Follow-up tasks waiting",
    body: "You have {{openTaskCount}} open CRM tasks. Clear overdue items in Pipeline so nothing is missed overnight.",
    pageKey: "",
    priority: 5,
    contextTriggers: { condition: "open_tasks" },
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "reception_calendar_overview",
    area: "reception_os",
    title: "Review today’s schedule",
    body: "Confirm arrivals, staff, and rooms on the calendar before the first patient. Same-day changes should be visible here and on Front desk after refresh.",
    pageKey: "calendar",
    priority: 10,
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "director"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "reception_tomorrow_prep",
    area: "reception_os",
    title: "Prepare tomorrow",
    body: "Use Front desk → Tomorrow to spot gaps, confirm deposits, and flag bookings that need a call before you leave.",
    pageKey: "front-desk/tomorrow",
    priority: 20,
    roleScope: {
      workspaceProfiles: ["reception", "clinic_manager"],
      tenantAdminRoles: ["operations_admin"],
    },
    dismissible: true,
    snoozeHours: 12,
  },

  // —— Pipeline (CRM) ——
  {
    code: "pipeline_enquiries",
    area: "reception_os",
    title: "Work enquiries in Pipeline",
    body: "Pipeline is the single door for enquiries and follow-ups. Move stages as you call patients; open an enquiry for notes and tasks. Prefer Pipeline over older enquiry bookmark URLs.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 8,
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager", "director"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "New enquiry tip",
    actionHrefSuffix: "crm",
  },
  {
    code: "tour_pipeline_empty",
    area: "reception_os",
    title: "No enquiries yet — take a short tour",
    body: "Pipeline is empty. A 4-step tour shows how to capture an enquiry, move stages, and book a consult — operational steps only.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "pipeline_empty",
    tourSteps: [
      "tour_pipeline_step_capture",
      "tour_pipeline_step_stage",
      "tour_pipeline_step_open",
      "tour_pipeline_step_book",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Tour me",
  },
  {
    code: "tour_pipeline_step_capture",
    area: "reception_os",
    title: "Capture a new enquiry",
    body: "Use New / Quick create → New enquiry (or the New enquiry control on Pipeline). Enter name and contact so the lead is saved to this clinic.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_pipeline_step_stage",
    area: "reception_os",
    title: "Move pipeline stages",
    body: "After a call or email, move the card to the next stage (or use the card menu). Stages keep follow-ups visible for the whole team.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_pipeline_step_open",
    area: "reception_os",
    title: "Open the enquiry record",
    body: "Click a card to open notes, tasks, and history. Add a task if someone else needs to follow up.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_pipeline_step_book",
    area: "reception_os",
    title: "Book a consultation",
    body: "When the patient is ready, create a consultation booking from Calendar or the enquiry actions so Front desk and Doctor lists stay in sync.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "ctx_open_leads_followup",
    area: "reception_os",
    title: "Open enquiries need attention",
    body: "You have {{openLeadCount}} open enquiries in Pipeline. Work the oldest first — call or task — then move stages so nothing stalls.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 3,
    contextTriggers: { condition: "open_leads" },
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },

  // —— Consultations / doctor ——
  {
    code: "consultation_forms_runner",
    area: "consultation_os",
    title: "Complete consultation forms",
    body: "Use consultation forms to capture history and pathway decisions consistently. Save drafts before leaving. After complete, use guided hand-offs for quotes and next steps.",
    pageKey: "consultations",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: { workspaceProfiles: ["doctor", "consultant", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
  },
  {
    code: "doctor_overview",
    area: "consultation_os",
    title: "Your clinical day list",
    body: "Doctor overview lists consultations and handoffs for your role. Open a consultation to work the patient, then return here for the next visit.",
    pageKey: "doctor",
    pageKeyPrefix: true,
    priority: 8,
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open consultations",
    actionHrefSuffix: "consultations",
  },
  {
    code: "consultation_conversion_path",
    area: "consultation_os",
    title: "Watch consult-to-booking follow-ups",
    body: "Use Pipeline stages and consultation hand-offs to see where enquiries stall after consult. Focus on operational follow-ups, not clinical decisions.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 35,
    roleScope: { workspaceProfiles: ["director", "clinic_manager", "consultant"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
  },

  // —— Surgery ——
  {
    code: "surgery_pipeline_review",
    area: "surgery_os",
    title: "Review the Surgery hub",
    body: "Open Surgery for cases, readiness, and surgery day (when enabled). Resolve operational blockers — staff, room, consent, deposit — before procedure day.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["surgeon", "clinic_manager", "director", "nurse"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Surgery",
    actionHrefSuffix: "surgery",
  },
  {
    code: "surgery_readiness_checklist",
    area: "surgery_os",
    title: "Confirm surgery readiness",
    body: "Check readiness for each upcoming case: consent, plan, pathology, deposit tracking, staff and room assignment. Missing staff or room becomes high priority within 7 days of surgery.",
    pageKey: "surgery-readiness",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: { workspaceProfiles: ["surgeon", "clinic_manager", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Surgery cases",
    actionHrefSuffix: "surgery/cases",
  },
  {
    code: "cases_worklist",
    area: "surgery_os",
    title: "Use Surgery cases",
    body: "The cases worklist is your index for active surgical journeys. Prefer Surgery → Cases in navigation; deep links still work.",
    pageKey: "cases",
    pageKeyPrefix: true,
    priority: 15,
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Surgery hub",
    actionHrefSuffix: "surgery",
  },

  // —— Money ——
  {
    code: "financial_os_revenue",
    area: "financial_os",
    title: "Use Money for finance work",
    body: "Money is the finance hub: deposits, balances, pathways, and collection priorities. Manual payment records are operational tracking — not bank proof. Verify funds before surgery day.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager"],
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "tour_money_empty",
    area: "financial_os",
    title: "No payment records yet — take a tour",
    body: "Money has no tracked payment rows yet. Tour how deposits, clearance, and the payment inbox relate — tracking only, not bank settlement.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "money_empty",
    tourSteps: [
      "tour_money_step_hub",
      "tour_money_step_deposit",
      "tour_money_step_clearance",
      "tour_money_step_inbox",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Tour me",
  },
  {
    code: "tour_money_step_hub",
    area: "financial_os",
    title: "Money is the single finance door",
    body: "Use More → Money for invoices, deposits, and pathways. Avoid treating badges as bank proof without finance sign-off.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_money_step_deposit",
    area: "financial_os",
    title: "Record a surgery deposit",
    body: "Create a manual payment record when a deposit is taken. Mark paid only after funds are verified.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_money_step_clearance",
    area: "financial_os",
    title: "Clearance before surgery confirm",
    body: "Surgery confirmation within 14 days can block if clearance is not ready. Resolve deposit or pathway items in Money first.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Surgery readiness",
    actionHrefSuffix: "surgery-readiness",
  },
  {
    code: "tour_money_step_inbox",
    area: "financial_os",
    title: "Take payment when enabled",
    body: "If online payments are on, use Take payment from Money. Otherwise keep using manual records under financial payments.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_surgery_empty",
    area: "surgery_os",
    title: "No open surgery cases — take a tour",
    body: "Surgery has no open cases yet. Tour how cases, readiness, and booking connect.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "surgery_empty",
    tourSteps: [
      "tour_surgery_step_case",
      "tour_surgery_step_readiness",
      "tour_surgery_step_book",
      "tour_surgery_step_day",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Tour me",
  },
  {
    code: "tour_surgery_step_case",
    area: "surgery_os",
    title: "Create a surgery case",
    body: "Use New case (or Surgery → cases) after consult so planning and readiness have a home record.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "New case",
    actionHrefSuffix: "cases/new",
  },
  {
    code: "tour_surgery_step_readiness",
    area: "surgery_os",
    title: "Check readiness blockers",
    body: "Open readiness for consent, plan, deposit, staff, and room. Fix gaps before confirming the booking.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Readiness",
    actionHrefSuffix: "surgery-readiness",
  },
  {
    code: "tour_surgery_step_book",
    area: "surgery_os",
    title: "Book the procedure on Calendar",
    body: "Create a surgery booking linked to the case. Assign surgeon and room so readiness can clear.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "tour_surgery_step_day",
    area: "surgery_os",
    title: "Surgery day board",
    body: "On procedure day, use Surgery day (when enabled) for live flow. Keep Money clearance verified before start.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 93,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_calendar_empty",
    area: "reception_os",
    title: "Calendar has no visits today — tour booking",
    body: "Nothing is scheduled for today. Tour how to book a consultation and see it on Front desk.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 1,
    emptyStateKey: "calendar_empty",
    tourSteps: [
      "tour_calendar_step_book",
      "tour_calendar_step_resources",
      "tour_calendar_step_front_desk",
    ],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Tour me",
  },
  {
    code: "tour_calendar_step_book",
    area: "reception_os",
    title: "Create a booking",
    body: "Use New booking or click a free slot. Choose consultation or treatment type and save.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 90,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_calendar_step_resources",
    area: "reception_os",
    title: "Assign staff and room",
    body: "Set clinician and room when your clinic uses them so readiness and Front desk stay accurate.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 91,
    roleScope: { anyRole: true },
    dismissible: false,
  },
  {
    code: "tour_calendar_step_front_desk",
    area: "reception_os",
    title: "See it on Front desk",
    body: "After save, open Front desk to manage arrivals for the same day.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 92,
    roleScope: { anyRole: true },
    dismissible: false,
    actionLabel: "Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "payments_inbox",
    area: "financial_os",
    title: "Take payment or record deposits",
    body: "When online payments are enabled, use Take payment from Money. Otherwise record deposits under Money / financial payments. Escalate mismatches to finance admin.",
    pageKey: "payments",
    pageKeyPrefix: true,
    priority: 20,
    roleScope: {
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
      workspaceProfiles: ["director", "reception"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },

  // —— Team / training ——
  {
    code: "team_directory",
    area: "workforce_os",
    title: "Keep Team records current",
    body: "Use Team for staff list, roster, onboarding, and access. Keep roles and contact details accurate so login landing and permissions stay correct.",
    pageKey: "team",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Team",
    actionHrefSuffix: "team",
  },
  {
    code: "workforce_staff_directory",
    area: "workforce_os",
    title: "Staff directory under Team",
    body: "Staff profiles live under Team. When someone joins or changes role, update Team and staff access so they land on the right home after login.",
    pageKey: "staff",
    pageKeyPrefix: true,
    priority: 12,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Team staff",
    actionHrefSuffix: "team/staff",
  },
  {
    code: "workforce_hr_sync",
    area: "workforce_os",
    title: "Review team compliance and access",
    body: "From Team, open compliance, training, and access tabs for onboarding gaps. Fix data issues before rostering staff onto clinical days.",
    pageKey: "team",
    pageKeyPrefix: true,
    priority: 25,
    roleScope: {
      workspaceProfiles: ["clinic_manager", "director"],
      tenantAdminRoles: ["operations_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
  },
  {
    code: "academy_training_tracks",
    area: "academy_os",
    title: "Training and competencies",
    body: "Training tracks and competencies live under Team where available. Confirm new hires are enrolled after onboarding.",
    pageKey: "team/training",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["academy_trainer", "director", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Team training",
    actionHrefSuffix: "team/training",
  },

  // —— Reports ——
  {
    code: "analytics_operations_dashboard",
    area: "analytics_os",
    title: "Review Reports",
    body: "Reports holds analytics, quality, surgery, and performance views. Use it for clinic trends — not individual clinical decisions. Reports is under More on the primary rail.",
    pageKey: "reports",
    pageKeyPrefix: true,
    priority: 10,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "auditor"],
      tenantAdminRoles: ["dashboard_viewer", "data_safety_admin", "finance_admin"],
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Reports",
    actionHrefSuffix: "reports",
  },

  // —— Settings / onboarding ——
  {
    code: "onboarding_configuration_hub",
    area: "analytics_os",
    title: "Finish clinic configuration",
    body: "Complete branding, timezone, and contact details in Settings so bookings, invoices, and communications resolve correctly.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 1,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 12,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },
  {
    code: "onboarding_first_case",
    area: "reception_os",
    title: "Create your first patient case",
    body: "Use New case (or Surgery → new case) to add a person, patient, and case. That unlocks consultations, imaging, and surgery workflows.",
    pageKey: "cases/new",
    priority: 2,
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "reception"],
      tenantAdminRoles: ["clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 12,
    actionLabel: "New case",
    actionHrefSuffix: "cases/new",
  },
  {
    code: "onboarding_connect_existing_systems",
    area: "analytics_os",
    title: "Connect existing systems",
    body: "Register legacy CRM, calendar, or finance tools under Settings for coexistence during onboarding. Verify credentials before any live sync.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 3,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },
  {
    code: "onboarding_verify_existing_systems",
    area: "analytics_os",
    title: "Verify connector credentials",
    body: "After registering external systems, verify credentials and scopes before live sync. Test-mode only until you go live.",
    pageKey: "configuration",
    pageKeyPrefix: true,
    priority: 4,
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Settings",
    actionHrefSuffix: "configuration",
  },
  {
    code: "patients_directory",
    area: "reception_os",
    title: "Finding someone in Patients — you’ve got this",
    body: "Patients is the shared directory for care records. Search by name or phone, then open the person for timeline, imaging, and linked enquiries. Small search, big clarity.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 12,
    roleGroup: "core",
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Patients",
    actionHrefSuffix: "patients",
  },

  // —— Warm clinical workflows (doctors, consultants, nurses) ——
  {
    code: "clinical_patient_profile_nav",
    area: "consultation_os",
    title: "A calm path into the patient profile",
    body: "From Patients or search, open the person you need. Timeline, imaging, and linked visits sit in one place so you’re not hunting. This only helps you navigate — it doesn’t interpret history or advise treatment.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 4,
    roleGroup: "clinical",
    roles: ["doctor", "nurse", "consultant"],
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "nurse", "consultant"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Patients",
    actionHrefSuffix: "patients",
  },
  {
    code: "clinical_imaging_upload_compare",
    area: "consultation_os",
    title: "Photos and imaging — step by step",
    body: "When media is ready, open the patient → Imaging (or Imaging review) to upload and compare views. Use side-by-side when your clinic uses it. Operational navigation only — never diagnostic interpretation.",
    pageKey: "imaging",
    pageKeyPrefix: true,
    priority: 5,
    roleGroup: "clinical",
    roles: ["doctor", "nurse", "consultant"],
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "nurse", "consultant"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Imaging",
    actionHrefSuffix: "imaging",
  },
  {
    code: "clinical_imaging_from_patient",
    area: "consultation_os",
    title: "Need imaging from the patient screen?",
    body: "Open the patient, then Imaging on their record for uploads and prior photos. Great job getting this far — keep media linked to the right person so the whole team can find it.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 6,
    roleGroup: "clinical",
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "nurse", "consultant"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Patients directory",
    actionHrefSuffix: "patients",
  },
  {
    code: "clinical_scales_workflow",
    area: "consultation_os",
    title: "Scales (SGFHC, Green, ADFHL) — finding the fields",
    body: "No worries if this is new. Open the consultation forms for your clinic’s scale fields (SGFHC, Green, ADFHL, and others you use). Fill what your process requires. The guide only opens the forms — it never scores or interprets results.",
    pageKey: "consultations",
    pageKeyPrefix: true,
    priority: 4,
    roleGroup: "clinical",
    roles: ["doctor", "nurse"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open consultations",
    actionHrefSuffix: "consultations",
  },
  {
    code: "clinical_notes_timeline",
    area: "consultation_os",
    title: "Notes and timeline — keep the story tidy",
    body: "Use consultation forms and the patient timeline so notes land where colleagues can find them. Templates speed documentation; your clinical content remains yours. Navigation help only — not wording suggestions for medical decisions.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 5,
    roleGroup: "clinical",
    roles: ["doctor", "nurse", "consultant"],
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "nurse", "consultant"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Patients",
    actionHrefSuffix: "patients",
  },
  {
    code: "clinical_consult_prep",
    area: "consultation_os",
    title: "Before the consult — a quick prep path",
    body: "Here’s a gentle sequence: Doctor overview or Consultations → open the visit → check history and imaging links → open forms if needed. You’re preparing the workspace, not receiving clinical advice from this guide.",
    pageKey: "doctor",
    pageKeyPrefix: true,
    priority: 3,
    roleGroup: "clinical",
    roles: ["doctor", "nurse"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Doctor overview",
    actionHrefSuffix: "doctor",
  },
  {
    code: "clinical_surgery_prep_ops",
    area: "surgery_os",
    title: "Surgery prep — operational checklist only",
    body: "When a case is planned, Surgery and readiness help you check consent, staff, room, and deposit tracking. Fix gaps before procedure day. This is operational readiness — never clinical planning advice.",
    pageKey: "surgery",
    pageKeyPrefix: true,
    priority: 6,
    roleGroup: "clinical",
    roles: ["doctor", "nurse", "admin"],
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "nurse", "clinic_manager"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Surgery",
    actionHrefSuffix: "surgery",
  },
  {
    code: "clinical_followup_schedule",
    area: "reception_os",
    title: "Follow-ups — schedule with a light touch",
    body: "After a visit, book the next appointment on Calendar and add a Pipeline task if someone else needs a call. Great job keeping the chain clear for patients and the team. Operational scheduling only.",
    pageKey: "calendar",
    pageKeyPrefix: true,
    priority: 8,
    roleGroup: "clinical",
    roles: ["doctor", "nurse", "consultant", "reception"],
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "nurse", "consultant", "reception"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Calendar",
    actionHrefSuffix: "calendar",
  },
  {
    code: "clinical_rx_admin_ops",
    area: "consultation_os",
    title: "Script paperwork admin — where it lives",
    body: "Clinic systems often track pharmacy paperwork and follow-up tasks on the patient or consultation record. Open the patient timeline and consultation forms for your clinic’s process. Operational admin only — this guide never chooses products or doses for you.",
    pageKey: "consultations",
    pageKeyPrefix: true,
    priority: 9,
    roleGroup: "clinical",
    roles: ["doctor", "nurse"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Consultations",
    actionHrefSuffix: "consultations",
  },
  {
    code: "clinical_medication_tracking_ops",
    area: "consultation_os",
    title: "Medication tracking fields — finding them",
    body: "If your clinic records medication-related follow-ups in forms or tasks, open the consultation or patient record and use the fields your templates provide. Navigation only — this guide does not choose products, amounts, or clinical directions for you.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 10,
    roleGroup: "clinical",
    roles: ["doctor", "nurse"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Patients",
    actionHrefSuffix: "patients",
  },

  // —— Experience tier: Novice (explanatory + Training links) ——
  {
    code: "novice_today_orientation",
    area: "academy_os",
    title: "New here? You’re in good company",
    body: "This panel is a friendly hand while you learn the system — next operational step for your role, never medical advice. Tips point to Front desk, Pipeline, Money, Surgery, and Team. Training has longer walkthroughs when tracks are assigned.",
    pageKey: "",
    priority: 3,
    experienceLevel: ["novice"],
    roles: ["all"],
    roleGroup: "core",
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Learn more in Training",
    actionHrefSuffix: "team/training",
  },
  {
    code: "novice_reception_workflow",
    area: "reception_os",
    title: "Reception basics — four calm steps",
    body: "1) Open Front desk for today’s board. 2) Check patients in on arrival. 3) Use Calendar only for reschedules. 4) Pipeline is for enquiries, not walk-in check-in. No worries if this is new — Training has longer walkthroughs if you want them.",
    pageKey: "",
    priority: 4,
    experienceLevel: ["novice"],
    roles: ["reception"],
    roleGroup: "support",
    roleScope: { workspaceProfiles: ["reception"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "novice_consultant_pipeline",
    area: "reception_os",
    title: "Consultant basics — Pipeline without the overwhelm",
    body: "Open Pipeline, work the oldest open enquiry first, log a note or task, then move the stage. Book consults from Calendar so Front desk and Doctor lists stay in sync. Operational routing only — you’ve got a clear path.",
    pageKey: "",
    priority: 4,
    experienceLevel: ["novice"],
    roles: ["consultant"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["consultant"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "novice_doctor_day_list",
    area: "consultation_os",
    title: "Doctor basics — start with your list",
    body: "Start on Doctor overview or Consultations. Open the patient for history and imaging before the visit. Use Surgery only for case planning. The guide never recommends clinical decisions — it’s here to help you navigate.",
    pageKey: "",
    priority: 4,
    experienceLevel: ["novice"],
    roles: ["doctor"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Doctor overview",
    actionHrefSuffix: "doctor",
  },
  {
    code: "novice_nurse_patient_flow",
    area: "consultation_os",
    title: "Nurse basics — patients and the day board",
    body: "Front desk shows who’s here. Patients opens the record; imaging and forms live on the patient or consultation screen. Take it one person at a time — this system gets easier quickly.",
    pageKey: "",
    priority: 4,
    experienceLevel: ["novice"],
    roles: ["nurse"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Patients",
    actionHrefSuffix: "patients",
  },
  {
    code: "novice_finance_money",
    area: "financial_os",
    title: "Finance basics: Money hub",
    body: "Money holds deposits, balances, and pathways. Manual payment records are tracking only — confirm bank/POS before surgery day. Closeout is under Money at end of day.",
    pageKey: "",
    priority: 4,
    experienceLevel: ["novice"],
    roles: ["finance"],
    roleScope: { tenantAdminRoles: ["finance_admin"], anyRole: false },
    dismissible: true,
    snoozeHours: 48,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },

  // —— Experience tier: Advanced (power tips / shortcuts) ——
  {
    code: "advanced_search_shortcut",
    area: "analytics_os",
    title: "Power tip: search anywhere",
    body: "Press Ctrl+K (⌘K) to jump to a patient, enquiry, or booking without leaving the rail. Combine with filters on Pipeline and Front desk for bulk triage.",
    pageKey: "",
    priority: 6,
    experienceLevel: ["advanced"],
    roles: ["all"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 168,
  },
  {
    code: "advanced_pipeline_bulk",
    area: "reception_os",
    title: "Power tip: Pipeline bulk follow-up",
    body: "On Pipeline, filter by stage then work a batch: note → task → stage move. Use list filters instead of opening every card when volume is high.",
    pageKey: "crm",
    pageKeyPrefix: true,
    priority: 6,
    experienceLevel: ["advanced"],
    roles: ["consultant", "reception", "admin"],
    roleScope: {
      workspaceProfiles: ["consultant", "reception", "clinic_manager", "director"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "advanced_front_desk_filters",
    area: "reception_os",
    title: "Power tip: Front desk filters",
    body: "Use status and time filters on Front desk to isolate late arrivals or pending check-ins. Pair with Calendar multi-resource view for room conflicts.",
    pageKey: "front-desk",
    pageKeyPrefix: true,
    priority: 6,
    experienceLevel: ["advanced"],
    roles: ["reception", "admin"],
    roleScope: {
      workspaceProfiles: ["reception", "clinic_manager", "director", "nurse"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 72,
  },
  {
    code: "advanced_money_closeout",
    area: "financial_os",
    title: "Power tip: end-of-day Money close",
    body: "Jump straight to Money for deposit and balance review. Manual rows are operational tracking — reconcile to bank/POS offline before sign-off.",
    pageKey: "financial-os",
    pageKeyPrefix: true,
    priority: 5,
    experienceLevel: ["advanced", "intermediate"],
    roles: ["finance", "admin", "reception"],
    roleScope: {
      workspaceProfiles: ["director", "clinic_manager", "reception"],
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
    },
    dismissible: true,
    snoozeHours: 24,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },

  // —— Doctor operational helpers (no clinical advice) ——
  {
    code: "doctor_scales_shortcuts",
    area: "consultation_os",
    title: "Scale fields are a click away",
    body: "When you’re ready, open consultation forms for SGFHC, Green, and ADFHL fields your clinic uses. This only navigates forms — it does not interpret scores or advise treatment. Steady pace is fine.",
    pageKey: "",
    priority: 5,
    experienceLevel: ["intermediate", "advanced"],
    roles: ["doctor", "nurse"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["doctor", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Open consultations",
    actionHrefSuffix: "consultations",
  },
  {
    code: "doctor_photo_compare",
    area: "consultation_os",
    title: "Compare photos when you’re ready",
    body: "From the patient record, open imaging to compare baseline and progress photos side by side. Operational navigation only — not diagnostic interpretation. You’re doing the careful work; the system just holds the files.",
    pageKey: "patients",
    pageKeyPrefix: true,
    priority: 7,
    experienceLevel: ["intermediate", "advanced"],
    roles: ["doctor", "nurse"],
    roleGroup: "clinical",
    roleScope: { workspaceProfiles: ["doctor", "surgeon", "nurse"], anyRole: false },
    dismissible: true,
    snoozeHours: 72,
    actionLabel: "Patients",
    actionHrefSuffix: "patients",
  },
  {
    code: "doctor_note_templates",
    area: "consultation_os",
    title: "Note templates — a little help with structure",
    body: "Use your clinic’s consultation form templates for structured notes and hand-offs. Templates speed documentation; clinical content remains your responsibility. Great job keeping records clear for the team.",
    pageKey: "consultations",
    pageKeyPrefix: true,
    priority: 6,
    experienceLevel: ["novice", "intermediate", "advanced"],
    roles: ["doctor", "consultant", "nurse"],
    roleGroup: "clinical",
    roleScope: {
      workspaceProfiles: ["doctor", "surgeon", "consultant", "nurse"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 96,
    actionLabel: "Consultations",
    actionHrefSuffix: "consultations",
  },

  // —— Next best action (rule-based; Today hub preferred) ——
  {
    code: "nba_high_leads_batch_photos",
    area: "reception_os",
    title: "Next: batch-ready photo upload",
    body: "You have {{openLeadCount}} open enquiries. When intake volume is high, batch-upload baseline photos from the patient or enquiry record so consults are media-ready. Operational workflow only.",
    pageKey: "",
    priority: 2,
    isNextBestAction: true,
    nextBestActionPriority: 1,
    contextTriggers: { condition: "high_open_leads" },
    roles: ["consultant", "reception", "admin"],
    experienceLevel: ["intermediate", "advanced"],
    roleScope: {
      workspaceProfiles: ["consultant", "reception", "clinic_manager", "director"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "nba_high_leads_work_pipeline",
    area: "reception_os",
    title: "Next: work the Pipeline queue",
    body: "{{openLeadCount}} open enquiries need attention. Start with the oldest stage, call or task, then move the card. No clinical advice — routing only.",
    pageKey: "",
    priority: 2,
    isNextBestAction: true,
    nextBestActionPriority: 2,
    contextTriggers: { condition: "high_open_leads" },
    roles: ["consultant", "reception", "admin", "all"],
    experienceLevel: ["novice", "intermediate", "advanced"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "nba_open_tasks_followups",
    area: "reception_os",
    title: "Next: schedule follow-ups",
    body: "You have {{openTaskCount}} open CRM tasks. Clear overdue follow-ups in Pipeline before end of day so nothing is missed overnight.",
    pageKey: "",
    priority: 2,
    isNextBestAction: true,
    nextBestActionPriority: 3,
    contextTriggers: { condition: "open_tasks" },
    roles: ["reception", "consultant", "admin", "all"],
    roleScope: {
      workspaceProfiles: ["reception", "consultant", "clinic_manager", "director"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 4,
    actionLabel: "Open Pipeline",
    actionHrefSuffix: "crm",
  },
  {
    code: "nba_evening_close_money",
    area: "financial_os",
    title: "Next: close Money for the day",
    body: "End of day: review deposits and open balances in Money. Manual payment records are tracking only — confirm bank/POS with finance when needed.",
    pageKey: "",
    priority: 2,
    isNextBestAction: true,
    nextBestActionPriority: 1,
    contextTriggers: { timeOfDay: "evening" },
    roles: ["finance", "admin", "reception", "all"],
    experienceLevel: ["novice", "intermediate", "advanced"],
    roleScope: { anyRole: true },
    dismissible: true,
    snoozeHours: 8,
    actionLabel: "Open Money",
    actionHrefSuffix: "financial-os",
  },
  {
    code: "nba_today_bookings_front_desk",
    area: "reception_os",
    title: "Next: run Front desk for today’s load",
    body: "{{todayBookingCount}} bookings today. Keep Front desk open for check-ins; use Calendar only for changes.",
    pageKey: "",
    priority: 3,
    isNextBestAction: true,
    nextBestActionPriority: 4,
    contextTriggers: { condition: "today_bookings", timeOfDay: "morning" },
    roles: ["reception", "admin", "all"],
    roleScope: {
      workspaceProfiles: ["reception", "nurse", "clinic_manager", "director"],
      anyRole: false,
    },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Open Front desk",
    actionHrefSuffix: "front-desk",
  },
  {
    code: "nba_doctor_prep_list",
    area: "consultation_os",
    title: "Next: review clinical day list",
    body: "Open Doctor overview or Consultations. Confirm history and imaging are open before each visit. Operational prep only — not clinical advice.",
    pageKey: "",
    priority: 2,
    isNextBestAction: true,
    nextBestActionPriority: 2,
    contextTriggers: { condition: "today_bookings" },
    roles: ["doctor"],
    experienceLevel: ["novice", "intermediate", "advanced"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 6,
    actionLabel: "Doctor overview",
    actionHrefSuffix: "doctor",
  },
  {
    code: "nba_doctor_scales_ready",
    area: "consultation_os",
    title: "Next: open scale fields for consults",
    body: "Before consults, open forms so SGFHC / Green / ADFHL fields are ready to complete. Navigation only — the guide does not score or interpret results.",
    pageKey: "",
    priority: 3,
    isNextBestAction: true,
    nextBestActionPriority: 5,
    contextTriggers: { condition: "today_bookings", timeOfDay: "morning" },
    roles: ["doctor"],
    experienceLevel: ["intermediate", "advanced"],
    roleScope: { workspaceProfiles: ["doctor", "surgeon"], anyRole: false },
    dismissible: true,
    snoozeHours: 8,
    actionLabel: "Consultations",
    actionHrefSuffix: "consultations",
  },
];

export const GUIDED_ASSIST_NEXT_ACTIONS: readonly GuidedAssistNextActionDefinition[] = [
  {
    code: "next_create_organisation",
    area: "analytics_os",
    title: "Create an organisation",
    description: "Every clinic belongs to an organisation. Start in the directory.",
    hrefSuffix: "directory",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 1,
    requiresSetupFlags: { organisationCreated: false },
  },
  {
    code: "next_create_clinic",
    area: "analytics_os",
    title: "Create a clinic",
    description: "Add at least one clinic under your organisation.",
    hrefSuffix: "directory",
    roleScope: {
      tenantAdminRoles: ["clinic_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 2,
    requiresSetupFlags: { organisationCreated: true, clinicCreated: false },
  },
  {
    code: "next_complete_configuration",
    area: "analytics_os",
    title: "Complete clinic configuration",
    description: "Finish clinic contact, timezone, and branding in Settings.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 3,
    requiresSetupFlags: { clinicCreated: true, clinicSettingsComplete: false },
  },
  {
    code: "next_connect_existing_systems",
    area: "analytics_os",
    title: "Connect existing systems",
    description: "Register legacy CRM, calendar, finance, or marketing tools without immediate migration.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 4,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_verify_connector_permissions",
    area: "analytics_os",
    title: "Verify connector permissions",
    description: "Confirm external system credentials and required API scopes before live sync.",
    hrefSuffix: "configuration",
    roleScope: {
      tenantAdminRoles: ["clinic_admin", "operations_admin"],
      workspaceProfiles: ["director", "clinic_manager"],
    },
    priority: 5,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_first_case",
    area: "reception_os",
    title: "Create your first patient case",
    description: "Use the guided wizard to add your first active case.",
    hrefSuffix: "cases/new",
    roleScope: { anyRole: true },
    priority: 6,
    requiresSetupFlags: { clinicSettingsComplete: true, firstCaseCreated: false },
  },
  {
    code: "next_open_front_desk",
    area: "reception_os",
    title: "Open Front desk",
    description: "Foundation setup is complete. Run today’s clinic board from Front desk.",
    hrefSuffix: "front-desk",
    roleScope: { workspaceProfiles: ["reception", "clinic_manager", "nurse"], anyRole: false },
    priority: 9,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_open_calendar",
    area: "reception_os",
    title: "Open today's calendar",
    description: "Review today’s schedule and assignments.",
    hrefSuffix: "calendar",
    roleScope: { workspaceProfiles: ["reception", "clinic_manager"], anyRole: false },
    priority: 10,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_open_pipeline",
    area: "reception_os",
    title: "Open Pipeline",
    description: "Work enquiries and follow-ups from the single Pipeline door.",
    hrefSuffix: "crm",
    roleScope: { workspaceProfiles: ["consultant", "reception", "clinic_manager"], anyRole: false },
    priority: 10,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_review_surgery_pipeline",
    area: "surgery_os",
    title: "Review Surgery",
    description: "Check cases awaiting readiness or scheduling.",
    hrefSuffix: "surgery",
    roleScope: { workspaceProfiles: ["surgeon", "clinic_manager", "director", "nurse"] },
    priority: 11,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_financial_overview",
    area: "financial_os",
    title: "Review Money",
    description: "Confirm deposits, invoices, and receivables. Manual records are not bank proof.",
    hrefSuffix: "financial-os",
    roleScope: {
      tenantAdminRoles: ["finance_admin", "clinic_admin"],
      workspaceProfiles: ["director"],
    },
    priority: 12,
    requiresSetupFlags: { firstCaseCreated: true },
  },
  {
    code: "next_academy_enrolment",
    area: "academy_os",
    title: "Enrol staff in training",
    description: "Assign training tracks from Team for new team members.",
    hrefSuffix: "team/training",
    roleScope: { workspaceProfiles: ["academy_trainer", "director", "clinic_manager"] },
    priority: 13,
    requiresSetupFlags: { firstCaseCreated: true },
  },
];

/**
 * Clinical Quick Actions — one-tap operational co-pilot links.
 * Warm labels; strictly navigation / checklists (never clinical advice).
 */
export const GUIDED_ASSIST_QUICK_ACTIONS: readonly GuidedAssistQuickActionDefinition[] = [
  {
    code: "qa_imaging_flow",
    area: "consultation_os",
    label: "Let’s handle imaging",
    description: "Open imaging upload & comparison — operational checklist only.",
    hrefSuffix: "imaging",
    roles: ["doctor", "nurse", "consultant"],
    priority: 1,
    checklist: [
      "Confirm the right patient before upload",
      "Use consistent views (front / sides as your clinic prefers)",
      "Save, then open comparison if reviewing progress",
    ],
  },
  {
    code: "qa_imaging_patient",
    area: "consultation_os",
    label: "Patient imaging folder",
    description: "Jump to this patient’s imaging workspace.",
    hrefSuffix: "patients/{{patientId}}/imaging",
    requiresPatientContext: true,
    roles: ["doctor", "nurse", "consultant"],
    priority: 1,
    checklist: [
      "Identity confirmed on the patient record",
      "Upload new photos only when media is ready",
      "Compare side-by-side — no diagnostic interpretation from the guide",
    ],
  },
  {
    code: "qa_scale_tool",
    area: "consultation_os",
    label: "Open scale fields",
    description: "Find SGFHC / Green / ADFHL fields in consultation forms (forms only).",
    hrefSuffix: "consultations",
    roles: ["doctor", "nurse"],
    priority: 2,
    checklist: [
      "Open the correct consultation form",
      "Complete scale fields your clinic uses",
      "The guide never scores or interprets results",
    ],
  },
  {
    code: "qa_prep_consult",
    area: "consultation_os",
    label: "Quick prep for consult",
    description: "Doctor overview → list → patient history & forms.",
    hrefSuffix: "doctor",
    roles: ["doctor", "nurse"],
    priority: 2,
    checklist: [
      "Open Doctor overview or Consultations",
      "Review history and linked imaging before the visit",
      "Open note templates if your clinic uses them",
    ],
  },
  {
    code: "qa_patient_timeline",
    area: "consultation_os",
    label: "View patient timeline",
    description: "Notes and history in one place.",
    hrefSuffix: "patients/{{patientId}}/timeline",
    requiresPatientContext: true,
    roles: ["doctor", "nurse", "consultant"],
    priority: 3,
  },
  {
    code: "qa_ai_patient_summary",
    area: "consultation_os",
    label: "Open AI Summary",
    description:
      "Operational overview of visits, photos, and open steps — never clinical advice. Use the AI Summary button on the patient profile.",
    hrefSuffix: "patients/{{patientId}}",
    requiresPatientContext: true,
    roles: ["doctor", "nurse", "consultant"],
    priority: 2,
    checklist: [
      "Open the patient profile",
      "Tap AI Summary for an operational snapshot",
      "Verify clinically — the summary never diagnoses or treats",
    ],
  },
  {
    code: "qa_patients_directory",
    area: "consultation_os",
    label: "Find a patient",
    description: "Search the patient directory when you need a record fast.",
    hrefSuffix: "patients",
    roles: ["doctor", "nurse", "consultant"],
    priority: 4,
  },
  {
    code: "qa_schedule_followup",
    area: "reception_os",
    label: "Smooth follow-up scheduling",
    description: "Open Calendar to book the next visit (operational booking only).",
    hrefSuffix: "calendar",
    roles: ["doctor", "nurse", "consultant"],
    priority: 3,
    checklist: [
      "Pick an open slot on Calendar",
      "Link the patient when booking",
      "Add a Pipeline task if someone else needs a call",
    ],
  },
  {
    code: "qa_pipeline_consultant",
    area: "reception_os",
    label: "Work Pipeline enquiries",
    description: "Call, note, stage — keep enquiries moving.",
    hrefSuffix: "crm",
    roles: ["consultant"],
    priority: 1,
  },
  {
    code: "qa_batch_photo_audit",
    area: "consultation_os",
    label: "Batch photo readiness",
    description: "When volume is high, work Pipeline then attach media on each record.",
    hrefSuffix: "crm",
    roles: ["consultant", "nurse", "doctor"],
    priority: 5,
    contextTriggers: { condition: "high_open_leads" },
    checklist: [
      "Filter Pipeline for open enquiries",
      "Open each patient for imaging when ready",
      "Operational media workflow only — not clinical review",
    ],
  },
  {
    code: "qa_consultations_list",
    area: "consultation_os",
    label: "Open consultations list",
    description: "Today’s consult forms and hand-offs.",
    hrefSuffix: "consultations",
    roles: ["doctor", "nurse", "consultant"],
    priority: 3,
    pageKey: "doctor",
    pageKeyPrefix: true,
  },
];

export function listGuidedAssistTipsForArea(
  area: GuidedAssistArea
): readonly GuidedAssistTipDefinition[] {
  return GUIDED_ASSIST_TIPS.filter((t) => t.area === area);
}

export function getGuidedAssistTipByCode(code: string): GuidedAssistTipDefinition | null {
  const c = code.trim();
  return GUIDED_ASSIST_TIPS.find((t) => t.code === c) ?? null;
}

export function getGuidedAssistQuickActionByCode(
  code: string
): GuidedAssistQuickActionDefinition | null {
  const c = code.trim();
  return GUIDED_ASSIST_QUICK_ACTIONS.find((a) => a.code === c) ?? null;
}
